apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: pgadmin
type: Opaque
stringData:
  email: ENC[AES256_GCM,data:vXq+H+nt5uuob0soLcK6Q63Z,iv:oDBz9zZUr2Mo1YsQ1GvZW06Ko/rlXyb/a9EJvlIdWNw=,tag:eFq6zC22NYdiAVwJ29zxWA==,type:str]
  password: ENC[AES256_GCM,data:6aaWhPZAOcOiNG93LSP+3U7rL5vqg/Ld/fzl2dfNYt2V2qnWwzVWaRYcf9en,iv:+h2pH1oA3+J1WWgiKSfa1VzJReTwaj67JNtTcvELyfU=,tag:GqQbhIYYxfkcGPkdsk+QeA==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZVZoS3YvSTd4OG5tL05j
        bjJ0M0JZdGVpdXJnRDBnSkdVMWZDWGdTWjNnCjJ0cDRBb3R5RmM5b2ZhZWpOYVJj
        NG1BRmliR0RWVDhVOS9hdE1hODJWK0kKLS0tIDgrY0Z1Wm1PYVR1SXR3RVNZQVFR
        NkdrM2IwNUx1WFZyb1AvMTdFd0s4bk0KHNgJQomrSsq57vg6HElmvszoVuK38KWC
        120g7ZaRtPeRBeErIEiSlbD6/8XMqh3YeULy2L2yLvuYI3ECjDtqjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-06T20:20:29Z"
  mac: ENC[AES256_GCM,data:kSqyoBnZmpDLfM+xb7s2hO2KoGbcaiSeMYy1HNi4Fmkc8G0kDl84vrM9SUwSEbJQsfwK0xtUP0OoAhHmXhWNn751hlE2+nJ1GkN1fb8Jb3m/xYWQWsGgHDKZAuoOdNPnSDsiPe51HEb9Xu6WN5yyJQ7mTJuBP4BmIZuORvtTEGA=,iv:qnZOWyR2AJ+otIwOdyVO/NuVvOsw5nENYHFipnk5wds=,tag:9aTpZW6fIuXFdzevuvuECQ==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
