apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-pgpass-secret
  namespace: pgadmin
type: Opaque
stringData:
  #ENC[AES256_GCM,data:FhCMud53j7lFOPbxY3SMjL3gJEtbGEnGQxNy3c+NSqVk11NSTCrnq05jjOrGCeQPO7njIK+7ya1XXVx7JF8=,iv:GYcZRr5U4uO2eeQ2QV833G/Wf1VaAo3qWZseR8JwtnA=,tag:Pa52Z4ObwZvbisb6/+4BPg==,type:comment]
  pgpass: ENC[AES256_GCM,data:nUbXvhLMdGHNXQ9PIFM1GOBJEJX8P9I=,iv:BKVBJ/KATmqv/RU8K1aSx1nKexcqe0AerLJTCmXy8mc=,tag:zqu/zPSGYqpFtFWNDabwJg==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dlhiaFYzZ0RYY3d4VWIx
        M3hBamVCQWsrOUFraTd6WW1hclpXTldVZTBnCithVVAxUVZEQ25SRHViVzQ4YmMw
        bFFKdG1nUjViVVE5U0hDVHFON0l5bjAKLS0tIFAwb2JKcjA5d1RGR2JscU0rZTNU
        aXhXVjdjcENaVnRzTmQ2SnlGR1NaVzgKFnwnSvUEmSqZAhbYIx44v/5s3y5oJMJy
        +3Hts+eMA/y1pUFoKl7E7E/Or7ntGFy82+7p0yEh9RG+y76pMcB3Zw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T07:14:59Z"
  mac: ENC[AES256_GCM,data:Lz0iHbA9nnmej/VHimx1i09q0qoJOp28iX+RidtNXyXMunvQvO4tFgcp3BbHzD5pSgODpqcKYkrzcOKuBE/uqupKfwz+1TxkfugEClsmnA+qP9ryr5TeJ4aYsQMyM9CYY7tBAJmpsSkc5aUjN3nuR/raau4y+oY/0wdOdXdvb9U=,iv:i4O8FQ6+dNcKvli+bmE/A5TJNTy1fRPgOIYP98QdmFo=,tag:4lTXS8fasmy19DFi3qs6OQ==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
