# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ccinvoice-secret
  namespace: databases
stringData:
  username: ENC[AES256_GCM,data:TWEIRGgo+QmL,iv:rMuDRphZaNVe3QA+nreq0SXsBlpZ3jjJEiRQNu/Jcfs=,tag:DcztuyRYUe+ovdCPqLtYyw==,type:str]
  password: ENC[AES256_GCM,data:ESQmBuKZdWFIUiOVk65SgFOgHVaLqlCy26kcEEEReNDAnh9A+bD2gvq1iIrTTyOtWMky3k8ie/Qenbj9VxANaw==,iv:txel4lSRAS13if+uZsAl+3ZzBC8BkuGBmlGzUm7UlP4=,tag:m3Ua6ZSDjx8heCuQHbQ/Nw==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4clVBUjc4WEJSeXprZG9w
        MGpqT0hGTUpkalY2NnJPSzV0LzJvbzZIS0EwCmo2V1FHdmxHVFdXaFFOVXRPdWxY
        bW5FblhETlZLblJ3S3JmV0puYmZZN1UKLS0tIEdqUjgyejlCdytDMUVNSE1iRkJj
        cjA3eXNpNDE4R1RZWmFnMW9LVVNIUGcKnZ+V92aRbFaCPFgIbwNGyXZ48EzaGS7v
        aJyljtV6BwfSv1AE7Dv5oMcvRlFb1l37Qv0beXE49R5By+btO+Z8zA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-06T07:11:24Z"
  mac: ENC[AES256_GCM,data:qScSzup5lkY/s6FM226o1N2rrZ6RGbysPAAQjJqw0Kt+zH5x2YZWB4z3E7YqeQJCpFUeQJYwyy/nuPy4kzMfuh6Ho5DBENxIaZxGVkawuQOroqpnx59Jlw0Vp8NhHWimU/50hkX0bP13R3S3WjIySLwnPaZQTsrZXt5z4XLLXB4=,iv:eyknHd+TpXFI5o5z76I8nm7ZDFLv6yqySqDOKCozQ3Q=,tag:epBFjviViU9mKXXSa884YQ==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
