# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ccinvoice-secret
  namespace: databases
stringData:
  username: ENC[AES256_GCM,data:EyegtNFp3G0A,iv:wYEp+x37YuV3g2tA0KK7UyGw+Y/eockLo75b1T7hEd8=,tag:oJU33TvEz+Ph6gvEFpZ3kA==,type:str]
  password: ENC[AES256_GCM,data:YDc2OPMZNt+df2XwewHUHh0wbOZ9MaIsKOgHis6CS/P6oPm+GZrXjUf6z5I=,iv:OjsAh2v9UqPIJoK88oRXK8AISpA62s5oIoogU3nhy6w=,tag:J9NTDjarQ2Rq72V5PXVBNQ==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNjIyVjBPbVJlUUJIZHpm
        elppY1dJc1QyLzFyVmI4OWNiMERpcENsODBBClJ2YU4yN2Z2KzQwbXBteVVMRlB1
        enFHb1FzL0RlaXg1NHorQURkYUpiY2cKLS0tIFdDR21EQy8zN0dPYmRFbWJ2Qmw3
        Z05oQTJRTGJqYXRZY2J1cStRdFgxZUUKCtSg1Rl3NqL+bOtXAe28Xu0RyAxdWAd1
        i58gcgYPIzFTZq2K/NEg1RSW455sVQbtFoF1Ml52pBm4HXPtX/fb5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-06T06:30:07Z"
  mac: ENC[AES256_GCM,data:MLqho14rfqJOK79bm6yySM66/ICGlVECFO3GFuiFqy59DRyWWhFfiKM/B2/w5SsJw57u/fSRxm6lpy/KTsHZP2psDVZtF4GKcRrcseCGSnuX+pCGBVyK21Yzn8fstsct4wV5ir/Qs9KG50rknlJwKOthGshucAuTJRecN8KPX3g=,iv:C0O0CqNMtL/TzgiSJDZxpMv3D9gFqI7W42nOTH9hFSM=,tag:VGjPNSr3b+FADnxM4Zn1tg==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
