# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gatus-secret
  namespace: databases
stringData:
  username: ENC[AES256_GCM,data:7ksqvYc=,iv:US1dooL6MiN5ECssIF4vKosOhcpYj412rrX32jMHHNI=,tag:xdNb+BAhf6gaKnbP0vsQmg==,type:str]
  password: ENC[AES256_GCM,data:8YFUr83DEObBn7tS9KJBfosxOdbEHo0hSQ==,iv:NgAcBeSspj0r2oSMMLpzDanEwBeyIaXU81JnQq4ZN0E=,tag:TFBYLZcsQ9smhe8eoIzEqA==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaC9taGhZTWxieGlhQmhC
        U3ZhVm12NVhRMFliQ3dKMkdXU0tib3BGR1NBCitRdnp3KzljNEh3UFRxS1VDR2NE
        MGMrUWFEZGhzS0o3RjhnRjNWQzFhZ1EKLS0tIHJGK2FnakJqTmxEcWR1UTJvWXdS
        bVRiWXJIYWV1SjZZMzBucDJKaGtMbjAKP5vz58Mu2lZRftshVsVVX8dkLLOPaICL
        eb+3irxpaw1+lZDy9CnunXMiAqnKZ/6pyC15jO382ufgBgqR3BStog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T06:46:28Z"
  mac: ENC[AES256_GCM,data:nr+znG05JTlYygayKCy9yUBFYzsCcW/XUoRxCM50McCQzMGO4kSUihXMU+5kgph5vcv3IR21VQZsUXptcNrG3E2uwleeFqZmPAz4QY3w157zn6bwV7v5AlOE7kgoh5+KPiU5R+zoNEoxwTZlvBXpcC3d0sUn8a/3CXu/9mL2+zI=,iv:Nxt0eYepDkuUPhT2Fhdn8BbDM/kKtyO5qHXl4OjXf0k=,tag:6nE9D2j6Wa4fqFXXNAwqwg==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
