# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gitea-secret
  namespace: databases
stringData:
  username: ENC[AES256_GCM,data:7h9kA8k=,iv:C0ZYm/CVLiMNUWHU7FQ826vfbiTBXOcubcx5cwkihzw=,tag:ZnvYcYTpcajgr23e7rZxWA==,type:str]
  password: ENC[AES256_GCM,data:1btoe+7ZcqHysXa546a5zAq6DGb9zYPlgpqxfEDeyA==,iv:7WFL69iFlHMOWcw6g2GiHDjid6DoanhgddBGOiFVoE0=,tag:AcUrUHvZf+Y8MmJVmQDK3A==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5THVtYlhHZ1NsQkdkcFQ0
        aDV3eHVPdE9YY3c5eTByUkljSVg0dStyRlZ3CjdCU212aUZLcDVYZUJjeG9rSVdN
        YVJxU0Njc0kzdUVVcGRCcS9oaDZSYWcKLS0tIDhtT0FuTWVKNDZPbVluNEJMdlVq
        ZG16d2JFSTVBRWZYa2FCYjhPbElTUE0KGTWOcOMk5hGsfw095WlgupBfMh2QRjxN
        YB76zV+EHZb42DWnXmmB3YSHoi+MTm+iolWDhl6CHZ0ClCV7J0GkoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T03:31:41Z"
  mac: ENC[AES256_GCM,data:lg+/E7J/mG06lb7AksRc2xBg+Pi3u8NnkZoYfpDUFh+OeQ0w1lIUN3v6uwheVWJZkfDB4EiGhi7fD/UxIYNJgmTpBZbpniRjXAHTLxMZpVL89gPBe5wIWlRZgdX98xdAK36XWiM+GCB7dmxvJyFdgQo27ejTleGSia3GySYlzXA=,iv:MGMTw8iTfAKK/FtyyIgpduqRj5Q3FjEDIBfHdwXA58E=,tag:LC3rL62SHXwmDeonLXU1ew==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
