# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - scott.secret.sops.yaml
  - ccinvoice.secret.sops.yaml
  - sonarr.secret.sops.yaml
  - radarr.secret.sops.yaml
  - prowlarr.secret.sops.yaml
