# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: prowlarr-secret
  namespace: databases
stringData:
  username: ENC[AES256_GCM,data:Rc7SeqI6Utc=,iv:UqRPDfXpc1koqyAbrcIx3YFNsh+87V97WoJtLpClFSE=,tag:2dIcww1IoKXG/Ze8UhD/eQ==,type:str]
  password: ENC[AES256_GCM,data:5MlYqpvmE2fEs+S5E2HQfp1OlCOzmeeHcarCttUsHy8=,iv:zPyrMX7uxGDUrGks/6HWWfoxcafZduCu5Pej3J1nSkk=,tag:i1IbFbhd1S6q05+WdvQFng==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBODV1RkNob0RKSUNoTHVv
        dzdNQWpIZ2NkOFFkMklVV3ZMRDZOQjBreVZVClhGMmNjR0lCbC9sNENCNFE5bE1D
        WXRuWjUvUWhGbHRWbklFM3JhL0k2T00KLS0tIEdHeXdmaDlwYkdUZ3NGYzVjb2lD
        RzMvT2xWTm81UXlDNWxVOTlYQVRVOWMKuead+1cGUBvhI9J9IGPaPs61KB5uJmko
        dK2gD/UK6bgT6yvSAJt7Vxbyz91DQVkbo3lNBE9RKaVT5pMCkCqTdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T18:41:23Z"
  mac: ENC[AES256_GCM,data:boQgvMJnPPwHdSvKh0fMpOSdfacMINecq1ElY7rNGEKPinzzPzfcefA42sKlUvLDh19rc8jnXZQYGRoAfXhkrRpYrcg4UV5innsU6/rS7SxYCsaQaQM7IY8cOVQA6wRNFKuKS10p7MD3RXy5GOI0WCsA1z9fd7xIwByRw/nBxNk=,iv:cbY3SeYoedJIPuX+RzKF61Sny7935R7y+rAWQnEJrzg=,tag:DhN8qCGXXWcBi4SSvIUZrQ==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
