# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: radarr-secret
  namespace: databases
stringData:
  username: ENC[AES256_GCM,data:tHytQ+qp,iv:Dm9Gp7u5klbGdXDXKwuyfrz8jX6d4axZdPqEBVopHKk=,tag:OYzOpcTNVAIXmT0BFMLuAQ==,type:str]
  password: ENC[AES256_GCM,data:TagYTZwzhl3sqptq4ffB9ulkYQ2Tpjx9,iv:BiAXRyb0NoBUhebfo9OjpYbyIui7H3lfBzhQ40u/s38=,tag:IyNomWl/dEVQgVeJnxehmg==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VkFEOTYzQlY4VTRkTW5O
        SktjcHEyaFE3L1Z0MXhuWjBKRWljUXVTKzJZCnVHbkRXZXY1aHhNakM1QUFMTU9K
        WC9wTVlHRGFXVkhkdFhxaWY2ZFNSbFkKLS0tIFhuaklwVVhieEZIZzl3dXhPZStn
        MUQ3NUlDRk8wZVpTU3luSnh0b0FkZUkKo1swY/+2SYXRMQ/K5ccam1Sbqx20ZY2I
        Hpvjdp3IK8a3j2adilgRwg66wmsxUUH6ugsE8/swU5jvnM2mvahhIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T07:14:59Z"
  mac: ENC[AES256_GCM,data:qt67VuDJNgzKssGoSjeX17mjzPkNsJyij5KholcIqYI+gduvxoTrKzQNUG6Q7lr74EnsBegqUCjESmE0xNTujMHroRuMsPc346e2BT4vTWJnHw9tpcYbYxCHKNPDeDdOCeNvLQW0CLTANmnjGIp9BAKchczL+02OgfxPhAEJOFY=,iv:UFeBMg3pQANaYKOvwGCvBBz+OYF7oUTuBf4RrxRhxws=,tag:XlLB2JQlw52qD9vag8Z4SQ==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
