# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: scott-secret
  namespace: databases
stringData:
  username: ENC[AES256_GCM,data:/biQnQ4=,iv:csyuMSO91mNwZRqvRoBdubKei58arx99Xj6ypwelQh4=,tag:IhttgvgY4MxozOJUvLclnw==,type:str]
  password: ENC[AES256_GCM,data:TYRq31iEov96Ir9qoC7m,iv:ibd8Qu3fKDRlrooSnlz1vooOqRfjrpWpZJcUx0rlfOo=,tag:urQyu3sw+FPjZSt7TDZLJA==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUlNuVUVPaGxPckI4eGU4
        QjJvNGJwSnRURlBpTDJkTm43S1ZDSC9xNHlFClcvZ2VFaS9TSkdlUnZRNkZGajJo
        WnM0RnBJR0V1SXJEKy8zTExrc0cwdEUKLS0tIHhWS2VhQm4rUmhXMUU5VVJPRlFu
        bjg1cUo4ZDV6eHYzZmJjbzhoenBCR1UKv9O4yq8s8vNfU9SbejOkYNulxBWw0Iig
        CwQXjhNFY8rQ4sm25U3oHnS2hMVaqzAvmY1+LuZmHxe0nHV1yc2/RA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-06T00:30:16Z"
  mac: ENC[AES256_GCM,data:aMV1nY9mcBPAJoQ3g+lwyyeca/QFuGrLTQNxH8Dfv7ae2hPeA2XXH7l3hfUKqCvA+mO6D8Lge01Qb7FGF6/tTvqieAHFyAh0JwGagIkkjzDqxzgOyCWe+bxJadyjfgFbxEj5rdhZ8dQYu3NjsLqKRj/2wI+DZvbXM3sseEkCf5Q=,iv:sU2Kz9JSZa2OxQkueb+528Jqv5YUV7WP9QRBGeizYBk=,tag:8nheqFWfXWgEWSRqhQ1VkA==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
