# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: sonarr-secret
  namespace: databases
stringData:
  username: ENC[AES256_GCM,data:jrTX6LRs,iv:ioycMLm53IQXn63GNmEm8lBjcw/pbzpMcYSHr8Caypc=,tag:46/G/rsZ8it2HM57CDyXmg==,type:str]
  password: ENC[AES256_GCM,data:E8gonYBNi1uBwNLhCdmaGd0OliCvn9/k,iv:JROejYH9rN4mEOCjpA/8WsEYhIIrDhNSPjc22Kabs0Y=,tag:3EtK16uHvpLgbHkorgCpEA==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUWJRWkd6cEpBeWxqalc4
        RHJpc0U2OVZQNXZTd0dHL3hkMEFteVlNSnp3CitMY1pPblFINm4rVjJsVFpGTE04
        Ujk5YVB1bFZBb1RtRlEybzVhVHR2K2cKLS0tIHRKZS9kc05idi9MbDdBb1hvRlBp
        Q2t1b1Y3M011ZnpwSGpSR2JwZXBTQzgKbTLkPjeVHW7MYeNC681r3/b8ynlp5RMJ
        6wLCvKNOwVyTP3i0lihz9rCMgCPZjry1O/SzI/Ode8FNq/l6/0jYew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T06:39:06Z"
  mac: ENC[AES256_GCM,data:pzsrcqnSA81va+zA8rn0pbe6zSRfAxUmLWG8EKXbH49aMYxfNrsf0XMLwlLc23BIXB0Crwt9JnS8KpCeUWtg+MWyoveZJmstIlRI2rSEhbl+SMS3KsqeydUHfYvyPv4DausRJGenNYVcu4HjmUeRj6iUcKJiJVNhgjxCp/wWXD8=,iv:It12jozRJp7Mqw6LNbDD3fl/ZVKFmc/Q7VNpo/PjkyE=,tag:8PMnSsGeiLRLB5dSV2YH5w==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
