# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: homepage-secrets
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
stringData:
  HOMEPAGE_VAR_GITEA_API_KEY: ENC[AES256_GCM,data:4yBXvFG+7z2ZDgXOYTaGIliykKgWrNDq4FUHLw8oF7DEPRJUtwoyMQ==,iv:TfBJkzUa7tKNsnWl4fONzuLH+Rw4c6ss9qUi/AwJGGA=,tag:ep3wpobEv/loG0c0oGxJiw==,type:str]
  HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:nBpGr1zRpqgdZr6DDE3T,iv:uxM8G73SBpgSRrt7kcbZDyYmbSBHfNMdemPi73bcAXw=,tag:i/7zpGOBXeCjAOxWbbxzog==,type:str]
  HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:ZIPfbLc=,iv:2Xj82APLHTvAD8lOcMCSvu2OJAMzmmruxYl+DSaXS1U=,tag:3u79PYdU+DMfGgLtIB6P2Q==,type:str]
  HOMEPAGE_VAR_HASS_KEY: ENC[AES256_GCM,data:3SNr/7jzwocnK2+DQvxPb40Vmq+n6xjPFfUMiQdOcynebvWz0dp2jisZzNetK3d1JqfHxswOxskwdeINPVu3dbeHbrzR9ryUsS5YUETD7QIrLReSad3fDOFxuohMEAuXCC8vwKKgA8XsZPCZtsCPjS8AGEhu+f4evBNjGZ4L/85S3uvIXuygPrPHTokye1AZb+u6Mq6CsfRgPeJII10nand9Y9wdL0wG1tY5tlD0zGuKSuAFs8ck,iv:AlAe6ov3wpRfGh6yPuavuVWHk0rZ/CPBBQ3qLJcnjm4=,tag:ijSDIFzV7NeNaGqR9R+T7A==,type:str]
  HOMEPAGE_VAR_JELLYFIN_API_KEY: ENC[AES256_GCM,data:ZKDCt9Wv4GGMZd2Js/9Pgx/F/rXbT24PFr0L/9bNk4c=,iv:SN8gLtjLq2h7cPuyf2886L3Ru8RHMgp+6AjP+e1+U0U=,tag:Z7NSom1S3oYL89ftVdupLw==,type:str]
  HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:aQr99oqVsAGvP3M/1L8Aum46kzT/jRjCmvtMQoyXxPc=,iv:NXSTWQ213IMq8Hpvp/Bp2aL7xezhP85nw3VRCIiF+x0=,tag:FbLwglN7DRxLHhSfwfdYIA==,type:str]
  HOMEPAGE_VAR_PROXMOX_TOKEN_ID: ENC[AES256_GCM,data:8ez4RcdkfH4Gj5vPnU1bdApnGDIk,iv:93h9GYoOstHy+UqwNquoZNmufHA6vT0BDiAy60n7V44=,tag:RrrgZQgd6S89OpIh9jo6pQ==,type:str]
  HOMEPAGE_VAR_PROXMOX_TOKEN_SECRET: ENC[AES256_GCM,data:LcQGGZFZ4veDsUUsfXQdq3DXe8usBIwLg2t7sv3TGDJ0fK7Z,iv:XRah8+jsVuGH1pHi5JrNipj08pWmbjruxYjJ1JTA+WU=,tag:her1yAdRj6j8AMS3OR4NqA==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:p3tBullirnatGW6lx4XC,iv:eqJFqR2tawOeEUkjVfsBsXkajO2sJhMDr+L7okhTE7w=,tag:QL7pCib899btfPRk61wn5A==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:uGIpwW0=,iv:o3PSaY3DDrj/kmXNUcdWG6/vhsVPLOIerg6kAJaHxOg=,tag:GfItF3rdT5N0+RgG8ltd8A==,type:str]
  HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:YZr0c6a/xKgC2Vp1ri0Fi4DB6o2a9HYHWXS/RLWahss=,iv:DxhHXfQrLvI3FR+PQboy3QXhZz1zO/1LOoyU02WD6/g=,tag:ReoXxoj++gZdlXkx5fQL4A==,type:str]
  HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:0u4JOkn5wfdsWB71yGu2uMC62EwJeC/Xz62dqLL6xhY=,iv:KltinjXjgklS0l2ScZZMTxfLKBcDyT/2MKRGxGGpl5g=,tag:pJWaCKNMKQiLLBovOdpWtw==,type:str]
  HOMEPAGE_VAR_TRUENAS_API_KEY: ENC[AES256_GCM,data:HdJEnkqxofSTFWl9lIqbmGErppnSC+eZK7ldvDqgAuAaj702R184b2GlUpmmb5vTfcALP8E6BNae8Dv3dn3/vRbA,iv:iwewBu50OkKiT1YsbrUqs0TjAKP04qpPsMll05G8hXw=,tag:wsnlfjVQC/ohe/QaKd61ng==,type:str]
  HOMEPAGE_VAR_UNIFI_KEY: ENC[AES256_GCM,data:TrmkeHS4kolHsO8BYXpiVM+MuDgg5uPQu/AUhkJdnr8=,iv:scS27O57sDpWu3srLzU+23pVyfiCbkA9swcvK+u3cvo=,tag:08zC1PQ6WhId6QM4jdWXBw==,type:str]
  HOMEPAGE_VAR_UNIFI_URL: ENC[AES256_GCM,data:CI6eVJi4t4cZi3RVTjwfH5sxH+RZhE9oUjOHV4VG+xrwtLA5179SWrfv4n1vZADOFRPm76Rg0yK8/LIDwf1IVQFbojCYR3cL2RWmWHDcb/Hh2LtK6M14/GzXlz7eXn9ySlDFZYkYr5647agWh1wvyest6FqrghXEJ8FEkpfeaQ==,iv:VKE83B1UabXFz3UsMxd5YPOxaXlvwr1k5Xo81gHHAWU=,tag:l0Br5lJRy/PR8fosyaOqHw==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNUN2di9PRjdJWEJHYTBG
        NVVWSEoxZitRMzJNdzhKSXFMdSthemdpbTJFCnJqS2JOVHczdXRXc2xWOHVFdlo5
        eXYxa2ZLS0k5SC9wbWRVVlg2b0tYMGcKLS0tIFIvN2x0RFNrbmFiYWJVMzQxWDdR
        dHo3cnphdnZuV2VMWWwvMnU1cjhCSjgKjP8MUej5Nqymm6njWKKtrkv6Xm8hjKgi
        JevJ0hpgBoYlhCbf3dmpK6KNRVah1FdXCxEn4GnoV3WUF6PnM3pO1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-06T08:27:41Z"
  mac: ENC[AES256_GCM,data:+rXVdGrs9Dw5iF05ejVNCCj4vko9c2LwCOgqqlGRSbpabzkVDBxc0nlk4o5OrcQ2Kz4on7gF9FCcn80aYAQIsijX2BsbnkGDG2/rv8OK9iNX+TaLQ7R9GS8jv9mOpuBMymHZK58eHtcZSZKqOpcb5cAaJIpNt7awvKt1LKTe6G4=,iv:CdFvV91SsE+L4YSOpLxRcRMU0OpxLA89hWZ4fbgJl/w=,tag:e4awSl6Vbc2uCqhejAIFGw==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
