# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: homepage-secrets
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
stringData:
  HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:+CIYCnAGwaO5l61Ot9CA,iv:NYY/EgbzBz2jTtm90jLdCZHnJ9EQYwTXpz8ovR5Tyv8=,tag:r+ifwNUmTfExYz1KDaFV+g==,type:str]
  HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:+y4zC6M=,iv:dqpYEkv+pDEr081AGDMpdXdqGHwuZBd/yTxktz+7Zho=,tag:cVaWr0LZjmp+tvbOE9hsoQ==,type:str]
  HOMEPAGE_VAR_HASS_KEY: ENC[AES256_GCM,data:MteobERlsxPEJeZKLDW2D5XtOr4DlovaS3wWtwcMkOgfJp9j6pzGyYoyBUEUa0+fzCFA6qewLEDRpvrDnBlV4nXhe+92rcTVCD9ndscjhoUnhS0Llrd9qUuMSWJfrr2Rcjq7VLfDf10CufYmJsrIWzZD4Oa1XPux/Weanu02eTAdWTBuBMbBxLaM87+f+qTKzsf2MiGmW9XwhjyEvNk7bBd48gUFgHZN3lON7EV8aFH9riZSlazN,iv:84Aax58TMJeTuY/XiFxfCNcIV76cYcQPWBAj8MWXWfc=,tag:sA/nZDW/eBqOIWqZCmvAZQ==,type:str]
  HOMEPAGE_VAR_JELLYFIN_API_KEY: ENC[AES256_GCM,data:eFiC6E80wl4OrAtlZprpupNdzw78N8JPRXaiDChkksk=,iv:On5HtaB259Pe/hKHpZUqNTtZ+Dyx4Y5kxmNhABaVIHI=,tag:PHMGgUUnXytoDs7QJiZQJw==,type:str]
  HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:KET30r0K5vqNgvs00ncsxt8ongp4fgvPtenpbqCuY8I=,iv:Xwfm80L9WtpLZ52PJvH1L29OcHijlHtGLEs/BFuMuKI=,tag:sWVqUPogHMjNj066T23YLA==,type:str]
  HOMEPAGE_VAR_PROXMOX_TOKEN_ID: ENC[AES256_GCM,data:akbuQSIbeZy1KZKGgGgISEKp2D+J,iv:mwoggHfyHihhTqRLWCr2y2xeMKPhZ7+Y028ro/OXvJw=,tag:+NUngY7+bBVRGIM6HwLYCQ==,type:str]
  HOMEPAGE_VAR_PROXMOX_TOKEN_SECRET: ENC[AES256_GCM,data:yYoEVSysHtITYt07zZgV0Zy6IJWNVnlBujsb6AB0MVgX3Ia9,iv:ESwgNc5nktYq1O2CQkoXpApyYzFpk1cD6Somi7Lmre4=,tag:ExxiXNEk1oNofa8aWffjLw==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:cuCekpWx1se+XM1i+z2O,iv:Nk67a/dcxihEOkPGo6MzsbJQDH/YvaQGMJ+leB0aPWc=,tag:2K5Yc2cR+qzzmKQX7xHj6w==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:HYLjbp8=,iv:M8fkY+dPMxWzhHIM3n8fQDohzR6N3PFTHVQDCn43SQ8=,tag:L3HOaqFF5Q9dpi2Wy73FSw==,type:str]
  HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:pC6R8lv6f55yqI/XwkD+4yxhQunrwqEti7JfsxLcEdw=,iv:xYjRrcM5RoibAhG9Ge6aYQfxqIjhazAkDmFtUZLqDWo=,tag:rqc6hoxy0TMaK9Pmwh2wrQ==,type:str]
  HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:TuYLmzOU+cLC0wuY9wwhD7BOvb+oQiUPxHQtehgC6lE=,iv:iP+21fRiVq5rc3iEo5v+HDoMPcyyxDeY25FYoV9tQwo=,tag:17htYxikiq39ethEM8yZqA==,type:str]
  HOMEPAGE_VAR_TRUENAS_API_KEY: ENC[AES256_GCM,data:EsaJW2DfmVfLA8IaNcfgQldOgVwtjL9yy/I8lHIFXEzCrtBxIVpdIiHooaM1vX1Bts9GAmUbFbDQ3x8SCw2Z4HHu,iv:Y6zciR/4MXw9eeJUzAI6J7QaIKjTeUzdU76NPUQZyB0=,tag:Ym+DRe5fd9/7qAhT+wjOvQ==,type:str]
  HOMEPAGE_VAR_UNIFI_KEY: ENC[AES256_GCM,data:jiLbMUxerP9kbz3vqTfGmpow/LvOtlGRyxCAfgrmlU4=,iv:rPNRGsB9lYsY2KYpflrBa0Mz4Anss6UxFrucIvApJSw=,tag:G48Mri1U2xEKeyE16QIKyg==,type:str]
  HOMEPAGE_VAR_UNIFI_URL: ENC[AES256_GCM,data:RA75zpMHNhkD4CVv9Knqg+n1z9xLpIHV6CRNgdSrpmEbGrrYkr4AGE1cn9zsS5K5vtd1f244r1VIPXYuof4M3CJ+j5fCygWOBawBwA1vXVy+SGHswL9wq4sBcPFOiLUXn450vxMbw+kHmDVzOGpfQPFirFcfZ3o6paByAu5rcg==,iv:f6bX5U+qmIn3ZrJrP8ez9y280ykLIL9SjfHfyzRdYm0=,tag:ShkopaucztDrFx0waPTT5w==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwamY1TzJjbG9QWUY3eU4x
        UkNNZEM5cjczOXk3YWdsWUJXRnA1RWl6b1J3ClV6N3NjOXNRYWsrUTF4c0NOOWhm
        elA5Kzh3QzlhOU9tOFNlSFlqUm45bEUKLS0tIFRrc3JpLzJtMXVmSDQvRE50ZW1Q
        bXZsSm9TdTc0d1NnL080TmNiOHUwZ0EKozGQ9sK6F/N8oyE159srL7DwY2FHUsuf
        Zgl48Df0kmsq7vYf/X9pC2RWJhQilPGZ+Jiz/Ai6f+i6RtnLEZYWlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T07:36:06Z"
  mac: ENC[AES256_GCM,data:fc10s2Qf+EMJV0S44rGrahgWwQ+y+r2DR3ninDzFyX3YacOopewn3JrB2R7Jv5nPTH+jDtQatArf+qvu4CKbRTjUgfff/KDnjWY9Jq40wLx1wh22dSufEYq3yWWrZm1JF4Q3l7IB7xK7LeUX1874t4qMmaCU29RaS5/Kx1omax8=,iv:uSNo/BdgG6oygi3er07iKG0d/OtosdhTVqVGl+xhOhg=,tag:t71G3AKKWROFcJWYOFyHSw==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
