# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: homepage-secrets
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
stringData:
  HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:teUnqCjKpFarsOgdNQHj,iv:1XyUAEbGy848YhbjQE3ForKYJtiJczfMMS+14THGrIc=,tag:OSwIKfe6fYnlmYB4lDdzVg==,type:str]
  HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:OdbuE30=,iv:qod/3pcNKL48561vmai5IF+J1/BjP6H09T2SARM91DI=,tag:2TmwMxSZlo1Le1ulzZL0mg==,type:str]
  HOMEPAGE_VAR_HASS_KEY: ENC[AES256_GCM,data:zeo90rKP8RdTwewh653IP9zw0K5Aa0sinUJFJHxb/0Rpw4ZSFg+CJZppgC+xmECAnCBXLwZmwMOUnVRbk/Aspn5MRuONFx9EunTAvQRuSiJ2X4iPHiHs/KxsfvD2OmxiakXYtVnKeyMtQUoUNCdxASHl7ivbL4ODOVwbw5R3lgs+cUwk0lgxRW44bXEaOrwl8y5Zhhx4YtvSpcLy4YEZW1mlOKCyhu2TGXOd4dDWAgWwehhNDmcj,iv:aogtPcwI00iPXbBjgY4oszeDSz1zB6JdkfYcAneKEpM=,tag:B10aqttYEgIbdDtDs1aQyg==,type:str]
  HOMEPAGE_VAR_JELLYFIN_API_KEY: ENC[AES256_GCM,data:uYxtsih+3b4EFPUio/+q9CFI9q7K0mbQNgdNNR57DsY=,iv:vxUKsiYdEGKMuuwPd3oP64QIpzVLs5/A8iWGO1dIDf0=,tag:kgddVmrTmDIR2aEe+nwF5A==,type:str]
  HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:A5mIONequrPY7oDC+O9P9IZQLmcUeIlFpa25lH2LtZk=,iv:EHZ5FzVzznBxS5E/zbnDwseAh/tm7HkXsCoo865T4kU=,tag:aJlHV9Uj7OmDpJMW2MWEjw==,type:str]
  HOMEPAGE_VAR_PROXMOX_TOKEN_ID: ENC[AES256_GCM,data:JeGRvVHW7FyBpjdAo1m6M47kg3o5,iv:o4t8rVDOI69qmysbCg3BDRt399++M4PkDhmXT4OXIM0=,tag:cYaY2HqZWc+VNznZDlygHQ==,type:str]
  HOMEPAGE_VAR_PROXMOX_TOKEN_SECRET: ENC[AES256_GCM,data:wXrlsnbOZvpPU2yUdH1dWddqO9IxHvn0sIlIRpuarhkvsSwa,iv:nccXyhFM5Yy+jY/AQ9bZW8W/nx8oIPB1GTMGh8a6qeE=,tag:uyDJPHcOHUJXtJ8JxSkQPg==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:v7BXr4s3c7KQTNqTkPhi,iv:NuvdRHOZ6bsFJDQ3vEMx2UkRfNzLSQG9i1VzRvSAttg=,tag:g7yLqPAsTrOHuWEAufH4JQ==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:8BbZzm0=,iv:Rttis+o6IbN7Sxa4uHQLisY4Ren8VWdxmGbwy976NFY=,tag:eeRC0OC6xK1Zpxp69bPqaA==,type:str]
  HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:A0Yh/2dP+7Cpwb3Wa9XKOFw58CDqFseowD7wnk4WvzQ=,iv:Hrf5LmvPNJbgR7SAa7DNnIh9N4W1KHMUFdXklpSeckE=,tag:Rw9gbLfzaWnzN4iuR6qzww==,type:str]
  HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:Eiljtczblm+ZTL01RJhr1clzY7Tiev7kcir7iQ6N1gg=,iv:RYKbNOdi/DKyt9TBdVXdrBBOB5abCrlS6Xss3kAWv4o=,tag:EEMV9F/D6F1tvDvVzbeXdg==,type:str]
  HOMEPAGE_VAR_TRUENAS_API_KEY: ENC[AES256_GCM,data:Gryr4N0KeSD/2A+GSA8qch24NAVX6wg9y+UiW5p4lTa9GB8n8vyAVcM6SIJJIyG9Ay+Nl4bujVGigh4xWtF31V0b,iv:o4KPjeh80lVTirFFjFDdhIP599hLqximE/AEI+YKDcc=,tag:nAri2fk2EE1HfCwZbODbjg==,type:str]
  HOMEPAGE_VAR_UNIFI_KEY: ENC[AES256_GCM,data:cURwrAv+C8EJV7sEWV2vcyCk3MDaPlUJaYeCwYVecI4=,iv:ieIacb8UDv15RKERWlSVXvg7gdEk11+9Jw879FalZ8E=,tag:AptVDtyAIG52tNCnDMzn9Q==,type:str]
  HOMEPAGE_VAR_UNIFI_URL: ENC[AES256_GCM,data:oDdIMt/3rEpqbEOTSoaN1KeGYIgjzEXwJpFPCDCf3+9W7O7iL+cApQGmTAIddv+nwiqWFmifb8CMIFTsAqacPHnBssvOKQFn6D3QLt4ppEIGLQ8Hj6UXvrNbeFBXKk7ovv1HKeZfRmdfyJMlkomyGgir5kRKi+OXejNeHwRQvw==,iv:+mX1wEp4e240yyP9vP1AcHavpKk4XSTaZYjDAbaoed0=,tag:K5Tt4iBoM8nY6iYmeRWywA==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcXJmeHExWjM1OVdTWElp
        SW1iTExxOTVVdDltbDJXTjYyNEtCWWNyV3pZCkR2NHJhcll1elZxQXQwU1lWWVJZ
        eGFhL2ZFd0lOdUdxSXhwaWJ5S1lWM2sKLS0tIFNjcVBpOVRyVEhidDVtWFFwMzJ6
        SEkxdTQrQXF5WHMydEdGVGNJaTNXaWMK5XtyfrOvyuOc8TEOrONHCPD5vv92r0uw
        ze4mzeOR/HPIsjoxRzA14GFaAq0uMLKkXhOaY6/fbGj8LIi59lmP+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T19:10:17Z"
  mac: ENC[AES256_GCM,data:S72rKRtCuh3FWo1eN/7ekKIPhPjBdL3JqKDvV7nyXx/Q/iq3xiRYjUBJfVDG7XjmEq9LR/8BvjvIdXLCD//yvVzAM8YtoFS6Bou0zVGHQVgJfJOtuPnybOm2aNU4nb6OscnZazhoxLoxt9uvmpEW2BFU9AKaiQ6VA8YDk4a/uTo=,iv:iLINifouANfQXx1shnB/5d1ppwwq6LVmIPBqb81Fz6w=,tag:m2S9aHsZlvK5GuZn6ak1lA==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
