---
# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: traefik
  annotations:
    gatus.home-operations.com/endpoint: |
      url: http://homepage.homepage.svc.cluster.local:3000
spec:
  routes:
    - match: Host(`axis.scottmckendry.tech`)
      kind: Rule
      middlewares:
        - name: ipallowlist
          namespace: traefik
        - name: forwardauth
          namespace: traefik
      services:
        - name: homepage
          namespace: homepage
          port: 3000
  tls:
    secretName: axis-tls
