# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gitea-secrets
  namespace: gitea
labels:
  app.kubernetes.io/name: gitea
stringData:
  username: ENC[AES256_GCM,data:lVwRj2o=,iv:Lzi4vCsAfz4agXN1AODQBVNEknIdT1BjqL02zDAwTx4=,tag:ofEMYL40URpn/118NSL3Sg==,type:str]
  password: ENC[AES256_GCM,data:le69djd9bB+CYdRUVu95,iv:uMKaCAkBi1vO8egh2k5hgWu+raRoJXkA0YzJUUXwcMI=,tag:RhgOLNxT5Fouo+Y2kDvvkw==,type:str]
  email: ENC[AES256_GCM,data:WB2foIftZrpGrTj6CZ1RDKZxWr8R,iv:/6mAWc6c+dYG9+N56g12X8Jv/rqqH78spFEMsBux7FY=,tag:O6FX3WLw93A2eBEoFjw0CQ==,type:str]
  dbPassword: ENC[AES256_GCM,data:/UEuogE47xgQrktWExIkpHGBlQTKuCeL5tp1kqjivg==,iv:eoZWW+Ych4OPzdRuBj0AAUH1pAmk2m9+/KXwOD1w8/k=,tag:zpY4ODq2T8KmHIrrmOgegA==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdHVHVHM0SGw2cXZIZnU2
        NEMzV0JIZDBONW5NNGE0VUh3YmZFNlMyUkVJCkhKYnFJNngwZmVGQk5VWHpIaTVM
        bDFiM0xpeVF0cDZEUnBpVDFHaUtMaUkKLS0tIHFLSmNIMHBtL2czeU1yYWlDQ2w0
        Sm5Ka0pCdUNEdXoxUWV4U21ZUEhwT2cKz7BOEGq8ibuzXt53vcPLnQJhy0dR6d5B
        mhEb5bskpNkQEUvzpRFfbrY144RitbpZUC5NFss8kLwrjsLBnwBC0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T05:46:10Z"
  mac: ENC[AES256_GCM,data:pQIpTrXCgwBMVfaPOpKPAk8Bc/41VGO77LpoRn3jofOvukNl+JiMwa59zpxZYF7yoqt3yZ0TFZQvgzsBeQ5yYDHWoel1mP/of+OxwUr4Y/4sOzRnoSg21nqShjl+GD51J/9g76sgfloDgfzYcnlgrPw09mHl0IYPtkelIPQsk6U=,iv:SbI9dfAr6cYJomr4MesWwTVPSkoN3io4VOmWr6FdoAM=,tag:6D/MJU5voBnCORyAFc3x3A==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
