---
# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adminer
  namespace: traefik
spec:
  routes:
    - match: Host(`db.axis.scottmckendry.tech`)
      kind: Rule
      middlewares:
        - name: ipallowlist
          namespace: traefik
        - name: forwardauth
          namespace: traefik
      services:
        - name: adminer
          namespace: adminer
          port: 8080
  tls:
    secretName: axis-tls
