# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secret
  namespace: media
type: Opaque
stringData:
  SONARR_API_KEY: ENC[AES256_GCM,data:ndYzpQKD99DGitwFBoaQxnMe2qreQRv1P0prx8Fb0dg=,iv:OiVKuhGY6vPoYtwPZLgqQoMurPYTlGVU01G5VcVpGbQ=,tag:CvdrO5n6gRa2BJWSh+/Ihw==,type:str]
  RADARR_API_KEY: ENC[AES256_GCM,data:syY8ufu9l+tap4mbEJfEQgLTiWd4251liekp8UJWBTM=,iv:U9mIychcSyjcwXcQBkvEQ/ryCqEoFMXnW8qKERaMcn0=,tag:9LDw9+9d6VWcGxQEAfaBbg==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QlhpRVdxV1kxL3VlYmwr
        aVh2T1ZNa3JuTEhPbzIwcGplSUZqOTFvZXpjCmZnYm5qRzRydHFZa2dNbUxiNXRj
        UGZ5SVllNGxCUzZqY3o0MFpZelhVUG8KLS0tIDBOSVRadCtUYjBmUWVjK1NzMHNj
        bzg4Y1o4TGl0WTg1bVozK1llY0ZralUK/82kZ6T4mC8KGP3R5q2eVr0ckGsvqXQP
        FJIB1pFGIRj7PjTbMgZEMp8jjw/QylpEmMAhjIZY+C3wCXmX7G0Y2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T00:48:21Z"
  mac: ENC[AES256_GCM,data:KhYYDGnlRwcghBZiVZHicTVrCb9M/ZNT3A24TyAc8uZkTb49sfAP/3y2i2qbrdUUgx49OwhXtvSZfQWluCXXrOaHTkQVO9w5cVEKTWKaYBd3f0y+nThZTteczIt9goNuUcJC1YkIEZ2FdIKGktA+RbUU5lP1r4Jcg2XaW4ZK7vE=,iv:uUyopx74MQAjM5ZhBuyOyHx/I7QitJGulYkpz11hjT4=,tag:+Dyat+8J5Zvz9JvNapJLmA==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
