---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  namespace: databases
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18

  # Bootstrap from existing backup in Backblaze
  bootstrap:
    recovery:
      source: postgresql-backup
      recoveryTarget:
        targetTime: "2026-02-06 12:00:00.00000+13:00"

  storage:
    size: 20Gi

  monitoring:
    enablePodMonitor: true

  # plugins:
  #   - name: barman-cloud.cloudnative-pg.io
  #     isWALArchiver: true
  #     parameters:
  #       barmanObjectName: postgresql-backup

  managed:
    roles:
      - name: scott
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: scott-secret
      - name: gitea
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: gitea-secret

  externalClusters:
    - name: postgresql-backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: postgresql-backup
          serverName: postgresql-cluster
