---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  namespace: databases
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18

  # Bootstrap from existing backup in Backblaze B2, using the Barman Cloud plugin.
  # See https://cloudnative-pg.io/docs/1.28/recovery/ and note below about the WAL archiver plugin.
  # Don't forget to re-enable the WAL archiver plugin after the recovery is complete,
  # if you want to keep using it for future backups.
  bootstrap:
    recovery:
      source: postgresql-backup
      recoveryTarget:
        targetTime: "2026-02-06 12:00:00.00000+13:00"

  storage:
    size: 20Gi

  monitoring:
    enablePodMonitor: true

  plugins:
    # NOTE: when performing a recovery, you must not have the WAL archiver plugin enabled.
    # while this is supported, it is not recommended to have the recovery source and the
    # WAL archiver pointing to the same object, as this can lead to conflicts.
    # see https://cloudnative-pg.io/docs/1.28/recovery#restoring-into-a-cluster-with-a-backup-section
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: postgresql-backup

  managed:
    roles:
      - name: scott
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: scott-secret
      - name: ccinvoice
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: ccinvoice-secret

  externalClusters:
    - name: postgresql-backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: postgresql-backup
          serverName: postgresql-cluster
