# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: restic-ccinvoice-ccinvoice
  namespace: ccinvoice
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:f0MLGG5e/n4TJsUOe3RXamHs53gdAIfLSRwke9Zx0n0DkT5oeslwQDob8DtFL9IzBJCkr9qCw1dXEhqGpz93L6BG,iv:HVDPGHrY0PLrF5wRJNKGe/uwo39ccbyI2wx5/i5mMmI=,tag:tk6BBXN4QXVgq31Rh+v0Fg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:vf7/bF6DQmIN/uI/jXhAcIQK5y7uNvhu6Wq2Yt6TjHI=,iv:PCIK/JOSFGb1EeSLOQqf05hVNFkcyj3muIeNSwJN0GY=,tag:YGdFE15dAI/1O01OLJcYcw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8h3FvDohAeaKZWfg6R6BphT+O/uNP8IcDQ==,iv:ck1G9x1nP+fVkxNEDv0W/oITrlCSl0T8klphcQfoqrc=,tag:cFsNnZucY2/a4Z+HJaWpLg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MEQtuFT9nTEckqwv4ARsz3nPf4H89xkmumw6x/29qQ==,iv:ral7n2Z4dmmf0zbzb4S8661tC7bJ0itibbBCmwJSUF8=,tag:tZ2039nbQwqb09BLpiKmBA==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YUxsbjBoRzRWVEczQjl4
        bHVQd1hKOUdrcG1BcHpuNm5NRGdPck4wb1NNCktETGxPZW5wQjVJbk9iNkY1QlJl
        bUl5M3VEN1ZqbW9SYTQrRWRRWktQY28KLS0tIHBTTFMrcTc0aTVIbEt3Qnh4U1dO
        ckhVV3JHUStKSkQya08yQ3lhWGdYSWcKI8aVOyMEjRTNOZJaX8AvfAs6kb4rQ6Y0
        5b5MlNl5YYIQz2jfCQLgSV7EtMdQqZgnPkhkMpjEHIloQsiEzTMN6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T18:26:44Z"
  mac: ENC[AES256_GCM,data:PmNnkIfk1uv8KIvbDav4WSS+AjhTXNf/r7nyEvFClfrGzrOJ3jTKm2n6Jvm3uc2tns06btFQwfsiXXp+fhLAsLB4tQlGKr9WkuTfJW/CSzyvIpb2f7cQds5XF78OQ6HitVEtMD8iDFYtjbxqxauaQ4MAdYWdFEfXysvwiohhiNc=,iv:NRzTcOHrsNYgwH1YKH3I4zHh2A6xZ4cBzwAbTeWcgHc=,tag:FmREjBMAwVenboMra3zvwg==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
