---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/configmap.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
  namespace: ccinvoice
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: disabled
data:
  NAMESPACE: ccinvoice
  REPLICATION_NAME: ccinvoice-ccinvoice
  PVC_NAME: ccinvoice
  SECRET_NAME: restic-ccinvoice-ccinvoice
