# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: booklore-secret
  namespace: media
type: Opaque
stringData:
  DATABASE_PASSWORD: ENC[AES256_GCM,data:KBG5HsEZ8WBcDbYCTf2P6aawwUEiKZJVmXjKR6s=,iv:eEsXNWaq7DjhDvBDUeAygx+jR+mgAQ/2FCm2Wwlad68=,tag:2odCuWNtvphi6MXn3DULhw==,type:str]
  DATABASE_ROOT_PASSWORD: ENC[AES256_GCM,data:nyDrGileJveO9S6KG23gYEEdJKGNNoURck7q+xxiyDc=,iv:Z6nWEHedD3fCTKCbXiNX5mLBwraYPLeNgh+BOPJqlWU=,tag:OR+3GsjwIc7lTIxizDcaeg==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb2I1L2wzYkcxaWFrMXBp
        ck8wYzlkdE1vTENkbGJCQUJoVitqUjc0NkRnCm9GMjdqaWxlbDdYZjQyL3ZoRGVC
        eTVKZkZGcUlUSzBxYUFVTVFiY3dqdTgKLS0tIG1odnRuazd4ZEhQdFdCcjd4bmdt
        N096YzMwcmlYSHRYQ2l1ZTBSTTNuT2sKN6t/4JR3eq4AfAEs1eQhz8tU0Kl4xWki
        Tt+b5WfG6pUn9dSwPvt7YNsxkUHblzkFcmAU1Pz81pH5E+FxHRMdTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T18:26:16Z"
  mac: ENC[AES256_GCM,data:ONKuO4ovcKjBWPFkwXaymnmSzMWayiNQP6b6rYSxSHyG3bNk+coXrxV+U0Fs4IV8/HSavY9kTXS08NCJPK0LvMDm/fl0/BaKqyXOhPGq2UUStSku6ICIj1MaihdcGRXUcpSarR+GVqfsUIR16NYaeTxG236talIHbZ9H4n9jo9M=,iv:g7Pe+HKOR5Lau4DpFY5rrIkiet0Wq1tJftK87AXRVns=,tag:q26E6nk+4n6p176cLD/enw==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
