---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: booklore
  namespace: media
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      booklore:
        containers:
          app:
            image:
              repository: ghcr.io/booklore-app/booklore
              tag: v1.16.5@sha256:3b95a0c0085b6972f19075db695a118a9fe589561eec7816e4441465ae915ecd
            env:
              USER_ID: "1000"
              GROUP_ID: "1000"
              TZ: Pacific/Auckland
              DATABASE_URL: jdbc:mariadb://booklore-mariadb:3306/booklore
              DATABASE_USERNAME: booklore
              DATABASE_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: booklore-secret
                    key: DATABASE_PASSWORD
              BOOKLORE_PORT: &port 6060
              SWAGGER_ENABLED: "true"
              FORCE_DISABLE_OIDC: "true"
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 700Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              runAsUser: 0
              capabilities:
                drop: ["ALL"]
                add: ["SETUID", "SETGID", "CHOWN"]
      mariadb:
        containers:
          app:
            image:
              repository: mariadb
              tag: 12.1.2@sha256:e1bcd6f85781f4a875abefb11c4166c1d79e4237c23de597bf0df81fec225b40
            env:
              TZ: Pacific/Auckland
              MYSQL_USER: booklore
              MYSQL_DATABASE: booklore
              MYSQL_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: booklore-secret
                    key: DATABASE_PASSWORD
              MYSQL_ROOT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: booklore-secret
                    key: DATABASE_ROOT_PASSWORD
            probes:
              liveness: &mariadb-probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - sh
                      - -c
                      - mariadb-admin ping -u root -p${MYSQL_ROOT_PASSWORD}
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *mariadb-probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 999
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: booklore
        ports:
          http:
            port: *port
      mariadb:
        controller: mariadb
        ports:
          mysql:
            port: 3306
    persistence:
      config:
        existingClaim: booklore
        advancedMounts:
          booklore:
            app:
              - path: /app/data
      mariadb-data:
        existingClaim: booklore-mariadb
        advancedMounts:
          mariadb:
            app:
              - path: /var/lib/mysql
      books:
        type: nfs
        server: 10.0.6.1
        path: /mnt/TrueBlue/media/books
        advancedMounts:
          booklore:
            app:
              - path: /books
      # ingest:
      #   type: nfs
      #   server: 10.0.6.1
      #   path: /mnt/TrueBlue/media/books/ingest
      #   advancedMounts:
      #     booklore:
      #       app:
      #         - path: /bookdrop
