---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

storage:
  type: postgres
  path: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=require"

alerting:
  discord:
    webhook-url: "${DISCORD_WEBHOOK_URL}"
    default-alert:
      enabled: true
      description: "healthcheck failed"
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 2

endpoints:
  - name: cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord

  - name: google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord

  - name: postgresql-cluster
    group: database
    url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/query?query=avg+by(cluster)(cnpg_collector_up)
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].data.result[0].value[1] == 1"
    alerts:
      - type: discord

metrics: true

ui:
  title: AXIS Status
  header: Status
  logo: https://scottmckendry.tech/img/logo/icon2transparent.png
  link: https://scottmckendry.tech
  buttons:
    - name: GitHub
      link: https://github.com/scottmckendry
    - name: Homelab
      link: https://github.com/scottmckendry/axis
