# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gatus-db-secret
  namespace: monitoring
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:2Hai7no=,iv:TrGmTaSzQlWjOLDeCU0NN7hVkwySFbDTZlgO9NCQ9BM=,tag:A4GvnhtSokU5SymSGgniHQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:EaWL5RVBa+yj7BrsOqafHcL0e/esDKjaGg==,iv:QNkiFkWJwO5qqP41DlnWmfY7fvBQU49piLLrm2t3/7o=,tag:gMM5o2V+fo1L6ibS4wUMkA==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:uXViNHMztjFDXMuQCUQPXIrQS+cU+o/+6ckFfwkGSc3lkhNFITt+9BJrQ9Ja1WGbTQ==,iv:v/FS8ftkXdAVaZO6orvA2ylvsC0O4EvcU10kcX6r1pw=,tag:D9LqX2FuaCiMZyYDVrCTGA==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:XfBltog=,iv:jA0jPcgXxnPHlccXij+CsDT4qJAlvMnt2Y5dS5RTTSE=,tag:IZDOBtnsOhaaakMCT/5OOA==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYVlzOTl4dVFTZWp1Snla
        SVpWd1NWUnFDVW1zamJsaU96cUxDb1lNK1NvCi9RWmgrWm5idjFtcHRra21BUHky
        QjJWWEZGblZUUVY5SkFYRzRsMGIvN2MKLS0tIG1wMXlNeTZDWFBqVGxqVGdIRGRD
        UjdadGFPVWsyL0JtVDFva25ZcUpjeDAKxox2oJj9CFmdg3D1dgc6WcGnragvdngE
        Y3JUjrpPXdt5me3GWkbtKLKNOBoA3A6HzeK0M1zHxwg+mKU0iuieDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T06:52:35Z"
  mac: ENC[AES256_GCM,data:pdQg4aCJRklt+afeN3EXX0fhge0Cj+V72uBA1FOMOnA8NfB7kIYNEwtcpNpzGyFwXrJBb0gqtYYVAO/6t2wRGdE5fQouxZgWmPYLDHYkfnji/gN9H/qKESWy0FqkN+2IUwc5VA0ZIQd0rw1rJ2Z9gkkio1sspFNDzD6xTrUO2l0=,iv:TwfvpiooEamO/HxFzxU3iSxVE898hz815NFmSOyhb9g=,tag:tv1JqRwUeX7pwBswe7UQ0w==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
