# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: restic-actual-actual
  namespace: actual
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:mEvldPoQjyqGU5IknsKSo9noVRCCOHm3SSsMhKfuN2H9VMUkRjfPGVjq6JiVqYOsvBL+Z1JaKtXVBCWo,iv:zcalqW9lxg0kmgT2GyPden2T5+DsRN0GXRcGwNC3r5g=,tag:CJ8tj1xO/iOfL6VaeNRTtg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:nzvLe9HIVvkqDSeqkd9hOO6b6S6YXbYiTzzFW69nQ1M=,iv:8P2HDEQBBCYXfplFgoY1tsUsgCuGaYuehPic5wdevgs=,tag:h+qa2PzryeuI3RFuUhqNOA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:bYC16J8Ijvp6kXgB0AnbNYEvh6/ifsJsqA==,iv:peKPphMATI/qekT7fuFDTZg0SfeQ/cFE8Y74DLZUmFA=,tag:OP3KnyO1ec5WyOUqibJosQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:W6/3la8IQNSg7lBwRrepfckGK/BEve7jbJx4d82DMA==,iv:c/D78V0JH5ERI6rXd3Y6wuNf5b0qi+X8h4M8ZZH1Hw4=,tag:Ov13PSnqgQQMSAlA1HOqTg==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVHNtaCswWlFuZ2Myaktk
        cGlzUngzcjJOdkxzV2ZGYVBMNXRHc0ZtSWlNCnJUSzN4SXlvRG51bFRQaVdjL21Y
        ZXpiM05SWitEd212SnFyRUdnRlc3c1EKLS0tIHpBVVVuZHpRY3djK2ZmRHliVnhB
        WlV5SDJ1WXJnb09MUzVFNWp2MjlWVEUKtX0VltVrkt3eny5EYdaE1WWF+tt+J84T
        Z1x0ug+AXKS47AA2JHpWCbRoEND7hirWZPpXgrqOasH+bFm1v2svZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T18:26:45Z"
  mac: ENC[AES256_GCM,data:73uxqtgKY0i5pRJdKenia6MDtKdDY/KIj2cVhjmdzaqdZDJLvaGVh6DSFMosZ+6J+fUiUx3uUJISM8/L3V/w9GX33+HpDBsIq0OQNl9RcI9hW3GxUkNolJU7r0BhBUNV1IiEWpAXyofkUjye+5xcvV/dVQsIvx+rLrOw+Hnxh0A=,iv:kYsnq1tx15I5dsESz1CRa7yO92OSRmSJon85YbNT3i0=,tag:PmqNuxjJaZVZQdjOh7YGpg==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
