# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: restic-actual-actual
  namespace: actual
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:R5jSUCl6+yzXC6rsp/KppiVBz708hjJe7fwMNOUqDHC56x9mgSHUKWyQUZq0+96yps+cpedFMp2hMGlR,iv:yO4CWnMm8zoyYpVwB+9n0HRRnvQ2kfgyoUFX3EzxgmA=,tag:9mEQyJnPnkBPL9cvQ9o2vg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:Q1pzab1q3mSs0SGmco5T3OtB0IUT7LcmpmWwL0fE1/w=,iv:Rpe7NRTCuInt8qKcJwc1snw7IXAcLRHJ7gZuDW2IKFQ=,tag:ZX0oCEoANt4D9PsR/hICjA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Fc301Hz5QTx6YJedYILT3RzvcF+mcGp2Rg==,iv:Y4R0GLhTNI0XnIHuBhyvKcMULPF1qlyMb0EICHEi4fo=,tag:yx2mMU4y1FaiwNo78b8gUQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+MeC7wy4xaKFQzru0srehBbSl5O2W22X5LrncFp/2g==,iv:QDrEPoYwsuwdHJw+xjhlgC0tLBFhCLpBWFDUP37sCuI=,tag:UsP+Qajr3l/ng98mfEhQPQ==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZStmOFU3SFd4Y0dJWVdP
        Y0VaS0VNaytnU3lRYWZsbmxiUUZYVWFvVjNFCnRmRnAvcnhWSm93S1dVRGFuWWVQ
        eGJhQmpGYjg1SEEzQml6NGJHaUtaVzQKLS0tIDhWaVRsMzhKblBrdHRZTTBaZ01w
        aHUzK0FIckVZaGxqTjhTUDBXRHpUL1EK5DEW31r+k204ovHSG4ViGY8hD6qH2miJ
        8SDjqJOT/I8Gw/9/PGroUGrxhlNbX4D40cz/wf7gkmIuZILMNjQhrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T07:26:33Z"
  mac: ENC[AES256_GCM,data:S1OZKZ5hqbpO783TJdTtV+PV8fbpIgM3E+m+F4gesBMRx92/nTYElb7OltxStdKqdRE11X/DRpUi/xRonJhKqndJtY/XIQIlwnCm4rTyjXFqhGNHdq9IRzAWpV5HUOk4N2CsuS4e6sa7ufo8yHK5duCzQwrTJn8/XsIrfeY/EQs=,iv:DAeROrrKpMOc9+t334J+Bh2w5PC/TSz8+8Aa7bj8Y/Q=,tag:QaH/bk6DyvoQ/I60kQ3edQ==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
