---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: tuppr
  name: tuppr
spec:
  chart:
    spec:
      chart: tuppr
      version: 0.0.65
      sourceRef:
        kind: HelmRepository
        name: home-operations
  interval: 1h
  timeout: 10m
