---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: home-operations
  namespace: tuppr
spec:
  url: oci://ghcr.io/home-operations/charts
  type: oci
  interval: 1h
