---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/service.json
apiVersion: v1
kind: Service
metadata:
  name: ext-truenas
  namespace: traefik
spec:
  type: ExternalName
  externalName: 10.0.6.1
---
# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ext-truenas
  namespace: traefik
  annotations:
    gatus.home-operations.com/endpoint: |
      name: truenas
      url: http://10.0.6.1
      alerts:
        - type: discord
spec:
  routes:
    - match: Host(`truenas.axis.scottmckendry.tech`)
      kind: Rule
      middlewares:
        - name: ipallowlist
      services:
        - name: ext-truenas
          port: 80
  tls:
    secretName: axis-tls
---
# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ext-truenas-jellyfin
  namespace: traefik
  annotations:
    gatus.home-operations.com/endpoint: |
      name: jellyfin
      url: http://10.0.6.1:30013
      alerts:
        - type: discord
spec:
  routes:
    - match: Host(`jellyfin.axis.scottmckendry.tech`)
      kind: Rule
      middlewares:
        - name: ratelimit
      services:
        - name: ext-truenas
          port: 30013
  tls:
    secretName: axis-tls
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/service.json
apiVersion: v1
kind: Service
metadata:
  name: ext-proxmox
  namespace: traefik
spec:
  type: ExternalName
  externalName: 10.0.20.1
---
# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ext-proxmox
  namespace: traefik
  annotations:
    gatus.home-operations.com/enabled: false
spec:
  routes:
    - match: Host(`proxmox.axis.scottmckendry.tech`)
      kind: Rule
      middlewares:
        - name: ipallowlist
        - name: forwardauth
        - name: default-headers
      services:
        - name: ext-proxmox
          port: 8006
          scheme: https
