---
# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
  namespace: traefik
  annotations:
    gatus.home-operations.com/endpoint: |
      url: http://qbittorrent.media.svc.cluster.local:80
spec:
  routes:
    - match: Host(`qbt.axis.scottmckendry.tech`)
      kind: Rule
      middlewares:
        - name: ipallowlist
          namespace: traefik
        - name: forwardauth
          namespace: traefik
      services:
        - name: qbittorrent
          namespace: media
          port: 80
  tls:
    secretName: axis-tls
