# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: pg-playground-credentials
  namespace: databases
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:aNwyUDrapi7HBFb1nN+6,iv:UZK+9Gd8VLtR/IWVZHe1yP9esxFqXiuyzU97V2yNB1k=,tag:cK8Wwty9QADApcoWxeVBWQ==,type:str]
  password: ENC[AES256_GCM,data:fe3XsOkxafsiqPa+qNF6g4bJoT8V2tY3hQBw7Q==,iv:bz+Sr5ZRznbzJovgzbSk9dJLZsCDjjGICLp8ct1S5uA=,tag:hUje6R0PYJdzvKbUe3b2CA==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSWpnVUxOa1p2ZDlLM0kx
        aGRhZE1xNXZwWFAzdVlHL2ltbVFVdytjNGxvCnJXRHhSaEg1QlN0VlVwL3pLeFNu
        K3BqQVlWTGIzbmNoT0prWVRNOTVUcmsKLS0tIFExTGVXeFEzSlNCbC9NN3NjZWVJ
        SldqOFg3ZnR1bXpXc2pFdHpzUXlhQ2sKW0MZKPrWJzFpNhlkLafCr8FmxE15560L
        UgFokAs9V+KUrDYAe4CAjdol8NjrGFPOyqYtenVq8hA+Hv6SQMAoLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T02:18:51Z"
  mac: ENC[AES256_GCM,data:XD6Cy241ziFURnesRw8JtKJkZPQlSMbObkAdj+iwdMasPWI7vJzqvUDouWwjz8ulIOfFA18ivhvsWYZeFqLNSrfyzWmiENM0P2wmodNnDsOeOq/ccAxi4eGUUoPz1aO16WhQoSuxSXqGC4jvdg3YbnLHWIIwz0pdL08iaLQUlP8=,iv:y1Bkkra0IPn/Sm338z2A+IblRMPJbe98rWUI+AlolIc=,tag:/2BXjrnOtBNrZO+6t6Tiyw==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
