---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: databases
spec:
  chart:
    spec:
      chart: cluster
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: cnpg
  interval: 1h
  timeout: 10m
  values:
    mode: standalone
    type: postgresql
    version:
      postgresql: "18"
    cluster:
      instances: 1

      # Initial database and owner
      initdb:
        database: pg-playground
        owner: playground-user
        secret:
          name: pg-playground-credentials

      storage:
        size: 20Gi

      monitoring:
        enabled: true
        podMonitor:
          enabled: true
