# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: restic-media-booklore
  namespace: media
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:74X7h4M5EzC59xFHIeoydBBOsk0oyfoR5d0FGVPZ6sp8aoQ8xtwQTOI0aTHdN89bIhOJlWKj3ZM9NgqTNQ==,iv:FXyU95+NmTxVyzE153yRVp2WyAbhY3FWKShmYAij1LI=,tag:xYdzGKmbVd2hXkwi5+gOyQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:CmvDlNq5A6NX3cQE6T3j55RTfJN8NtKrL2Qlm/Et9rg=,iv:J0QL3N7sGkAO8TA5dyIfwaM2D6oyaJdKzuAYxFbKjl0=,tag:t6fBOeQ5OVWVtTrpJ4Dluw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:s19IGgMw/U6dd48ghzyBl7GI2eRfs1KqhQ==,iv:7CsRHsk3BLyXbqKz7IBvVOV5ZS+M02dSBdJB/Xj49w8=,tag:NdmVFxzf8grfoHqTs/LfRg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uLML8phnRNZPziJBx8qR/fBclfiPxfkJBy6SYWu3Fw==,iv:l90SIw2g4e0z6F+DALvOLD7FYCEdwNAsr32drQVxLGc=,tag:ZVqsnaEECa6Yf03nT/WtYg==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudXBqTGFlRm9rbFNCWnhI
        UkI4L1cyYjRtOXBRdjZabkMrTXFxOWQ0ZlhNCnlZMnA0d0Y2ZHhtWFU4SDA2TWtK
        elVUY3dwREtmVVRIU3FMVkRhSTNhdm8KLS0tIDZPZDVaRGtPbDlNdEdGZnp4ZGlS
        K2w3U2RyS09ybVU2RVdvMW12Y3BDM3cKC0Wu/gJu0rNjRu/KaqZ6wtkRouw7Cduz
        dhpNw1fMPOYVZbNE2DzxvJakp403IXdfxoLAmMOHaX10IBYZDqyhJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T18:25:49Z"
  mac: ENC[AES256_GCM,data:auZAsYy/TNy18OqLLrgxqoZmZk6WGDMc2A7MgPpadsM34/V4HyPHmcc10H7P/9/uiq44J1djr0gWdrIeJuwSZObTbpwgDqM8vD/BCaLdhvSg/Zklv/I1OTml5C0nSYISeQV8gv9j26oL3jcxU6Qa2La0Gpv+uF4DiAS8N0dgT4o=,iv:/WlwJpeblCH6n6zIr0/kt9NPVsptIy9RxVw+E9iad/E=,tag:anIzj8Mn7jwxNb399eJ8qw==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: restic-media-booklore-mariadb
  namespace: media
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:WQ1ith3s72WvrxnGuWaTTqW87gfUotVQ/k1/2K9JvhOgXCPUW7Er9xwankE62oR0w7JIVL95PONvwIjejZLS4BJozNWZ,iv:Uo3l0rn4et1Uq540VVnaBhlYtWZfv+byFIY5jFvAJk4=,tag:7WWJTsGfSH54Kxtq3EtPiA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:QwQzptjbOv9TJLOtJxJjzu2n27dMYyw/hrCl1OCyBIs=,iv:4qJzu9wD7Fen9okKQSuePmX6GhlU3WOUfP17CQ46nzc=,tag:h9yr50ptwCJalWkdU1sxcA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:f6msBWFGvwlnJSfor+V0oSHoFpH7IQrDCQ==,iv:BwmSlo3DeXr7x6mcwNGZMQllegL039SpMZjYvas3Mdk=,tag:gYSnheVsGbHTBdnThz+wFw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:M6GM+tJRSjqvGfv3hgqil9jzvjGr50vb2UicIjXJxg==,iv:t32fIif8Eat0Iv5NOi2Hf95iCJTJzwj6Mmo9YyLscHM=,tag:tfrSlagwOmLB5GtazW//ng==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudXBqTGFlRm9rbFNCWnhI
        UkI4L1cyYjRtOXBRdjZabkMrTXFxOWQ0ZlhNCnlZMnA0d0Y2ZHhtWFU4SDA2TWtK
        elVUY3dwREtmVVRIU3FMVkRhSTNhdm8KLS0tIDZPZDVaRGtPbDlNdEdGZnp4ZGlS
        K2w3U2RyS09ybVU2RVdvMW12Y3BDM3cKC0Wu/gJu0rNjRu/KaqZ6wtkRouw7Cduz
        dhpNw1fMPOYVZbNE2DzxvJakp403IXdfxoLAmMOHaX10IBYZDqyhJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T18:25:49Z"
  mac: ENC[AES256_GCM,data:auZAsYy/TNy18OqLLrgxqoZmZk6WGDMc2A7MgPpadsM34/V4HyPHmcc10H7P/9/uiq44J1djr0gWdrIeJuwSZObTbpwgDqM8vD/BCaLdhvSg/Zklv/I1OTml5C0nSYISeQV8gv9j26oL3jcxU6Qa2La0Gpv+uF4DiAS8N0dgT4o=,iv:/WlwJpeblCH6n6zIr0/kt9NPVsptIy9RxVw+E9iad/E=,tag:anIzj8Mn7jwxNb399eJ8qw==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
