# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgresql-backup-secret
  namespace: databases
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:G9MawCef0mgAteEWTggvVbTJlMDksDPNtg==,iv:nJbFyUKi1bAgdG0pOeV/BR5kRXEN8zGrHtbbI+hQ7e4=,tag:1k3SRjxMULFqXcme0G1cUA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:8AMkBYJIKE+FsU0Z5Tr3D9OqmgLz532kV7+5zxfqrA==,iv:RnL5RguzxEM8r3Ug85mRF9DzfhHWlZsD2d2l0N/eihI=,tag:xo/0Fqp5l1w4soie5ElY3Q==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdS9SRFlvbTlEdC8rWXBi
        d3RoZCttNWhRRWwzVjM5TXZybldOV1JwYWtrCmF6a3NNeHg3d3BkVG5GcmhyQk1E
        TXp3T3FYbVBKMFA1MWhUZWh4Tk9ibkUKLS0tIENibU5rVVdOYk5RRTlTVEtKTmNE
        TkkrQmlVNTBmdUxSRnNXZ2JMdDJEeEEKNybZul0qTTpVTDUalW45UVwNcfgAO32r
        S+5jelnllO86+msKTsrynpWHrbWs1fvM79TMzuVToWUF+jya4gt8Bg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T18:26:44Z"
  mac: ENC[AES256_GCM,data:iw+hwYglz6Q8R7zEPyp0Ty+vQJM4Z90G5CbA+bdQL7SVuh0M/uSGnht16p09DUg/Wci4bEMLcNdYlCHlK8NuAfn+VBOdGml6tk3MivfatC0yQ3li/IahdBcUlKbwrihTQ8dOgQ3UigmOrWhu4i9+yFZUYxGwmUVig8vcAO1aP80=,iv:wfK+s0rauGxiP9piQ2uO7+3RgMMgdkEse+OjRlkGXHU=,tag:mGcjso7meBfgu0+Sc2jH2Q==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
