---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgresql-daily-backup
  namespace: databases
spec:
  schedule: "0 13 * * *"
  backupOwnerReference: cluster
  cluster:
    name: postgresql-cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  immediate: false
