# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: restic-media-prowlarr
  namespace: media
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:xaPK35l8KGWwaVINUDUsxjXaF6VZ8dl0DzuBMGIqec8bs+Qxts72cZQ1f4FFqkazgrzO9Ek4qwK2F1GplQ==,iv:o56iFBx16f5oU9F/wtw6b9I0GVfc3aR8o0sh5Fi7Cdc=,tag:6WObc1Mi3qgDNHf4eOq2PA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:ADrmIWwalTnAdQGkVKVpIL6nWkFNiaSu3Kq61qNfj+E=,iv:0Vjcchmc59+12gnO7egLQnxx+ys1d2vKt1npDgU03mA=,tag:z/ZN6YiY9JDE5BtLmuPPzA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aPJgZVFR/bOB/xH/pjTEqalMgNifsnHv/Q==,iv:iHLWpGmMy4/SVMpkQmBryLjofT9jYxnomgA63+P6zEI=,tag:JDn5gmoaJRschhELXZ9F8Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:XFrSyR3gk1OgfIOur+RospMn2wgh4b6HUGDkkqTu5w==,iv:y+F0U1z5Per78JkfOue+h2Mdeq5WdRr5KD1INlP7MH8=,tag:WnmHD0d8rxhn6l0f2jX7ig==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYXFGRm05RlBHQ0RjQ2Z0
        QkRnbzFjbWx4a1g0WUU0UE8vYWFUbmFUaDNBCnlVbnBsMStsRFNzV1BFbkoyazc3
        b0hwL2pPazM5TlNRdmhXYklKejJtWncKLS0tIGJoek5TODRRdVQyZXNnSEFaYmNs
        K3ErL2llRHZLZDd5Z0ZWelNuMWtMUk0Kyz3zEWzGYGJoNjFEEVfpcUZJeNnM4sEW
        C83e/FmYNXm0q2ZpDLSqTmfVO4/iYouWSHGyQcJMA8fOrzLS9C+vdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T18:26:45Z"
  mac: ENC[AES256_GCM,data:u9pNqZvJ6c7KgOmyDw0CuAdD4wdu9OEuHFY+8/WAKXI9bG7Bg3By0tvEtDDl6CCbozv5CXQIxq7AJtSGjCwHudb8GKKmXhTFqOYIXGawHqiS9N0f2zH93s8rNvxLRFJ0g+3C2TbebgEubAdgIXOZlGV3SVLAAHUwUB8KcplqSqU=,iv:IBBD9+//h4KpqSMsyJQdSFPSobt1uh1y/OY+e+S58eo=,tag:+7P6oPo+09JRQc71lQTWpw==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
