---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/configmap.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: prowlarr-backup-config
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: disabled
data:
  NAMESPACE: media
  REPLICATION_NAME: media-prowlarr
  PVC_NAME: prowlarr
  SECRET_NAME: restic-media-prowlarr
