# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: prowlarr-secrets
  namespace: media
stringData:
  PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:m5euGRV3OGydKJjo4djrXqTgJdZc5ffqFYgV0Q+dHWjUzV2+nl/iZoJHEzLLJiUmMQ==,iv:FWQPYHMqssWrKkye8Oh8WzhcbKYPgG/JkCOoHCMHQu4=,tag:eDvBn8XTMitLFE3l81y9Vw==,type:str]
  PROWLARR__POSTGRES__PORT: ENC[AES256_GCM,data:NZk8+Q==,iv:Rc4oHbSqEmRXqzBq/X50wSmQVwWnNEfvaykadw4cM60=,tag:lZjog9Geq18ZgkEzPVDkag==,type:str]
  PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:o677TscoqEc=,iv:lXSSodTCpaFpYUuERDsgmG0bU4jlnSJaNTTZ1O1KWZo=,tag:/wuxNfSCkUok7WKiiPXdSA==,type:str]
  PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:MVTVkqDacEJ8+SH532cuYi4LeRFyPwHMFfRMaDlUYZc=,iv:WmYWwXWqdABMIe01Itkf7B2Bzz7LtQ/nLK//iFy/LF0=,tag:UcpXneBqOjyjQJ0vF2SukA==,type:str]
  PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:1Oyi+T6nJwZ4MYZjNw==,iv:vK3Q5OC5LkLfDDGSLPcZ5FVasbi4l4RHv0ItNfY+QQs=,tag:JeC6a6shGMyEaJPOFtsb0g==,type:str]
  PROWLARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:atfy9NPbXUE2Y03d,iv:Q95eXVpIouZ2KwBBoFlIxWpKENx/YC61DhgLMNlDVSM=,tag:gt/t0mx+QNObrwu6tYjCNw==,type:str]
  PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:9ihBBsWr4lCYkRXqARcVTCBK1x+5utbrC5xolp82oDI=,iv:drNjQyj1UFVf25jREbquwUfJSDf/I24OsWmKB83IqCE=,tag:rfk92KxgwVvht0f80ZQPrQ==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QVhLRTcwZkN6R0paaDc0
        RFlXQlM5bXBVbjZxRndKV3NPd3Y0UjRnejFZCm9GeVZJeC96Nk1CaFoySjV4THFT
        RTVGYUR5WkVSNjFNQ2NJYW1OazJtSUUKLS0tIDRxUW53MzlCbGwxaFA1VER6UDZ2
        SE5WT1JkemQyamQ4S3k2VFhja0FaeTgKEQFMBgkbbvKbIn/OTMk7HwkAw/0q2A1z
        VOw6sBHoVL/JvihZBilg+/r1UlF/wxLOgmVU/pVIoUp4CphCWHnMYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T19:10:17Z"
  mac: ENC[AES256_GCM,data:jti8nItzyGBWMbcVclxp1MLFQEnIc6HdEucvlMmI3+JjbXazrgiUJ52u4ztPhvFwPziEI3LP77uGmhTv4g0fgLzab3he3Qq0B8SjsCJzQlCDBPOVFtpykNfLpTlqc2T2Bpixt0ec+s163SjkPYghpg05Ieog2NeR5NOTgZPjcx8=,iv:LAvz1y/XYO3ZlRqYxZBn7umVhZZHKqrVsr7YOjRPfjo=,tag:Vg5iqmIo0KjWIm407/sEwg==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
