# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: prowlarr-secrets
  namespace: media
stringData:
  PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:3vElah9xStOQ3GE6OcX40KOd0mH/mlde1dLhoT3r+4UBZMOWM4WYb3lG3BGpFyZYhg==,iv:87IUZ2d5czwEGbKwTcqJiipYnR8LDWY/9c0JOTwTNP4=,tag:GDW+M5rBI/Rf9FRh/AvSOQ==,type:str]
  PROWLARR__POSTGRES__PORT: ENC[AES256_GCM,data:TZY8sA==,iv:gD3wicI+7QrpeH4xIRQiVLHZDzQ0hno83JvGIWEMWCQ=,tag:hUk5MPSTiDtv+5+6Cy/7hA==,type:str]
  PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:qFYMIqylIHQ=,iv:wmNo76Y9m6tUJ4V0Kgrgqc99kmuGgnrbmbfVnxIHfNM=,tag:IWw0uzEQDd71CK9tp1bR9Q==,type:str]
  PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:VV9t9Bs/0pEb/A8YKOt/qSh9CdBWUg7o6I9TCxCpOUI=,iv:trJVaysTNIiXt9k3rb2A4geJ3A7+9pOjXI32LckngEU=,tag:YMv1AuEOw6kC7cYmlNtmpg==,type:str]
  PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:BpC8vYcLhEV+50YECA==,iv:cIhRWBJZCHTKdqTtV2V30cR3yG9FabEQZWLlD6PQwAs=,tag:OaV08oAVWrrifAUmh70Udg==,type:str]
  PROWLARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:IW5R02Lx4bvi5Bg/,iv:MgCnLCwCFy4l+yrIT6CcO2p562fHwGxxw5/c31Xx3X8=,tag:P8n5CQ6yoBD4AOeOkuFxcg==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd0xTVW5qWWxQRDVRR1ZN
        OVNqcjVTMWoybnVmWGR1SE9rQW5rRGNNT0g4CmttQjU2dGFlMnFMelhOZ2ZFOG9L
        eUttN3VkOWE5eWxwWFpkTVF0UW4zYjAKLS0tIEs5dExGNVlVdXdiUlJiMy9TKzZS
        UHNRTG1sUFYyU3pHUnZWMDllK1REcFEKAtI+E/Z0ErLOuqji7xbkexjmdZ0DBtHN
        PFZi/ZXe10o9AueeSGEPeyiAfC1dm05Hc5tqKmg2tNK+1gwlQYwjAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T18:42:10Z"
  mac: ENC[AES256_GCM,data:SSCffFqygrS1nvg4CadiyzOGUQ07rEF3obOZ6S3hOzrbJ5zYpLF272kNyL4Blr/UxXwmI+xrDrIdlsf3tet0kdQriBocGhYUIEG34UY88+Cxhv5VSKemevwGQJDwZtdGGHd49QMuUSy7L26jevMMCvldB/BNY4awgOi+YGAZPMY=,iv:N7UJ92ufnOA9J+wEUcwVsKuZGrHS8wNlQll34ARdZEc=,tag:6OvJ4PZqVgeJcTiZe4RC9g==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
