---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: cloudbeaver-cloudbeaver-workspace
  namespace: cloudbeaver
spec:
  sourcePVC: cloudbeaver-workspace
  trigger:
    schedule: "0 13 * * *"
  restic:
    moverSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    pruneIntervalDays: 14
    repository: restic-cloudbeaver-cloudbeaver-workspace
    retain:
      daily: 7
      weekly: 4
      monthly: 2
    copyMethod: Direct
