# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: restic-media-radarr
  namespace: media
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:gPfMqAPyJdMm1ETOmkHzG8MsRxiuqstRH5797NcAmIhYpbcoDOC5+2MVIAMD9sO1dQqjmQHkJUOFymM=,iv:LhLFeiCmGyY82JyBU4jLR9JJJQ03dpC7eD5SvJ67BGc=,tag:nDKH36stT+p1pPFF81AjOw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:yrcPCB8OTxgVzlBFEZaTRRzlOv3wNZqBTMVfmhYdd/A=,iv:GQx2hInurIzUvP+8Zx6mO4tjyJvbYIi3QDzXHv55u00=,tag:Yo3TQwJvf6mzjq1+kcO6/w==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:53HTJm6TXmk3Z+Csd6QCGHPEFcX7e+Mh9Q==,iv:hgx5zaXW9k20b+zEdP5ls3Vpfi6A/2j13LGcvDQ3Bbw=,tag:1XdEQ6w+GKdflbBGcUovRQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:13CwebpblIf4SW1VXB95jF0voOTC17Uo69sS0vjAmg==,iv:XlYkleLdb0KmwhJOAJ3SD+mr30QeAOJ3wMMUQ1T7nwo=,tag:CFDDHWHooVAYox8Ax8trfg==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYVpOK2Y5cERVMTJ3RmpR
        bXBNQ0RyYlIyaFVMaEhxNjlSSUhJVmMxcTIwClBreTYwWE9BOWwvaStHOXBVRWJ1
        Vk85WEFBcktLa2dIOS85M3lKY2ViZ2cKLS0tIE9NZ0xnb2E1cWVMcW5VN2l1M0RX
        d2RVVmZQMkdoOVVyM0s2WlczK1hBTTAKghZFI5UqX0f1B5mvieF3wRwODcO0r6kT
        IDCymhTbFNZNym+dlTx4Jt8b4CGeX8+l9vxCV11YcqaiIzUY+XCpXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T18:26:45Z"
  mac: ENC[AES256_GCM,data:I80MViilb+000WiSPtxqkml7wrRhu7za4lvAc4V1WFklMLSbZV17cl5NodqYT3SToRYAIoJbttZFANwjKcSVA4jUL6ju9l7rTE3u6gg9oUezQqM8CtbbBEtJ/7aMQpccWhzTZLV7LDXhafh4vR7H4qs6q6ZgX4kbHa59Tn1Dfbw=,iv:Q9w9VgaXpvybUPlCDHFDvH4IZblcz6yfYNwM+HNZXnI=,tag:McyEG9uTmiBHTxUCI39/jw==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
