# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: radarr-postgres
  namespace: media
stringData:
  RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:vXjfqo0DrIMOCc/AGgA6vI0fHOddD8St1TjlnwQ/0xnttvQ05chXDBUYlXzhwu80dA==,iv:onF/nA9e3MMIMYl+OXyzv5tUNTwXCmF72eoff6/TGF0=,tag:SuXG1Kv/xg3K2d5kzhCRQw==,type:str]
  RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:lmisVQ==,iv:X//3KCClfWQfoWkPFbF+NiSUy+kl4lonMQrmUDICVJ4=,tag:0VTLoPYzN+ARkqtIcKa1Bg==,type:str]
  RADARR__POSTGRES__USER: ENC[AES256_GCM,data:rxHpZZip,iv:R3Virg7LGfxvh3JY3b4hgR/qOjNPsDqoZvJafOBaPeg=,tag:pzGbmY7KqqzC6rrFzMoKkw==,type:str]
  RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:VMiRPAtQBtFCaITwQmhrQgQmoou17ND+,iv:N/anIdfcf5DVAdE+JV0JV4At/9DQu90qS9QhBVBYLIs=,tag:qxtZpvYoRzYWUJp+XpptIQ==,type:str]
  RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:Zih8wm+1uHrrGEE=,iv:jxFVhdbFUqtMzR42LjwQDT1m6xbdNm4ByRHf/+r04mk=,tag:TOw47n2HSn8JVrlYgv36HA==,type:str]
  RADARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:QD+ZWqxnmqNLNQ==,iv:nWSPR7eWcjmLObwHfZoApkHomBeP3aQYIp5GDP2TauI=,tag:ZbfaBHLsgOXTDNl2TKS5cQ==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYWUrV0VHLzlkWFRaV0hx
        QXpOS25lZTlGTEp0Vmt6aHFkQWozL1lwSUJZCmFPSUlLK21aaGVNYzZyWUZyNGxR
        Z2R0MTdvWHQ2TkFDeTVPNk1RREZ2SzAKLS0tIEhjQWJUOTZrR21Eem9GYjQ2bU44
        cWxKUTB0MlgzejVHMWlZY0RZQ0tPQ00K2mIjSpO2mWAlmaSfTYMzVVxRXWSVe7TN
        YUeDTIO6nfcAAuQyGmzdhF4FuUaFmIKjjHeWMXrxaX88m8BRpn7MWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T07:15:00Z"
  mac: ENC[AES256_GCM,data:V2aJSXUaOBiwk/uU+9SewaS1wwiaHzTptvV9XCKzgUhvtiwfmv+6S5dPcXIfjeSD+418PTrAurlm7W6p5zIniqRMOcQGMvxuGTifRhLVFy7nYOcdjpbkVkxD7LvYUbAA9AEhnkB8UWcjeLvJPeYKjt1miY+Ef+47At5OSiIfGFs=,iv:KzfC/uyNTRGpwzM9boKCgoM9kMNQleGs3dTnaMSPYv8=,tag:rRRrUIIC1Av4jO4Me8nb/g==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
