# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: radarr-secrets
  namespace: media
stringData:
  RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:d5q1PVsxrNxAxz7SDDXctRFmvpnW0CsP/nVduO5sG+796WnVDoL8VcUr7cg0BWwTuQ==,iv:ICn66Q0SdkIKmzJUuLeawEAxezMiJKJnVI1tFCzCkDc=,tag:av8njgkp/TsJ3O30Ju7TTA==,type:str]
  RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:zofR1w==,iv:vJBT6gvJwcC0q4cFWiK423ytN3PC632RlcYAk4JT6xc=,tag:pdgbULpBsQX2kuc43ABZvg==,type:str]
  RADARR__POSTGRES__USER: ENC[AES256_GCM,data:HJ3RToze,iv:HxBQKo+kRUj0UZQH6CdohnrSqYfkT77Ebx4fRs/295o=,tag:m2BIGR7Fw9jX2I937R8/Dw==,type:str]
  RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:sAHINeAEur90BJM9ujp50qKzVQSKREaR,iv:MakcXwlxzcbJk7zO5h231aqOf6BnU+QZF9AxQdVDZ+o=,tag:HU0gZmNegmqxHrQ3v8C//A==,type:str]
  RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:33LDxOmDV99a/m0=,iv:qC1E8m/F1HWbhtRaa//+k9mUHFB1GcpvyK+CkxT0RGk=,tag:1Rk/FKt79x6zSQWXOVpIbw==,type:str]
  RADARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:gl7W7xYtWmVt6w==,iv:GAi1vEiKf45rh8kqqlptRDkYgifOHRuhEwKcS53IZI0=,tag:41rHavynKoaLb3fwd4S/yg==,type:str]
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:OgAeFV2fIrPhcASuTWlwUczVagekFehrvAlsjl5B84s=,iv:pBNyyabdN7yKEk9PqOWFVEYC0E9QnTvPf9PBPh41n1k=,tag:OfNq39SgD3+pMtyKeLjQzA==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjODZSSjVPSmUvRGNHMXQ3
        S2tpdUtWUmJ2RlpHVWNIMmtlY0NUTWdTYmk4CnZCaUZFdGdIeFFBakdheEZmeHVn
        KytyRHozYi80VWFSdDIybDZuT0p6cFkKLS0tIHY4bm43U0tjTGRUUW96UDJJQXZE
        SExKT01JZ0swdE5XOExKZkc2c2cvaTgK76fyAn9yuZPobiXDqjXaOEPdP4A3ubwu
        3cZyyCBxO4PxgW/jLJhagYCu4N970xFPpE9fXNhKFKGURuhscDEQZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T07:32:52Z"
  mac: ENC[AES256_GCM,data:CqOUdOEkjewCdB8Euhv+u5Pn9mfJ7rT4pCNm316N6AthwoOQttzUKXEGCEzkDoIZB6xn3equXMqOBe4wzAQVnyZfbO5NkfMcPRoXSJbwguuNmU9RQUbOWV+JLxmmYZOAHV4bw5y1M3FBRey780GRF5axjo4ao/PK/k1IFaTh/Jc=,iv:RPMMj4W1E3kTYvW12FCizNNpsZxV/Mm4MN2uNUiJTwA=,tag:fPRaj+anszFmDfKxelV6ZQ==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
