# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: restic-home-assistant-home-assistant
  namespace: home-assistant
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:QZH8eydDK8+y21Ar5kAP2eS/Iw3h0c0HlNgFhIf3LVLiDySqk+1zciVS1f98KFpEu76exQiSOQVElcsYTm+mDQLvXjFsD1nn3uqIXg==,iv:9hs+xelC5SxgCLqQUTetRcu/IcdcTpWVmoH0PYi7rrQ=,tag:uR5f6GvPFAomtvaDBFUhzQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:z3wqDJ+cWZANVvbMDrZ3iGcZpACZgHXKdRKT+h4dL1s=,iv:MpgqjAQIXqpLoPbLlMOQ1ynWHso4pMumWAClvdMYEyg=,tag:0vVtdOy9vEwoMa/WOs/TIA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:piZptYB/pVLDCSAxEa/uM0HRwr3XgcaOIg==,iv:QpXo7JOL92WRw6sKUTdrtrRSYsXAbKimWPqy9E6X7Lw=,tag:H8xgfDGuuvUQqysIqnwStw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CoBpxH3sKfmXg6SCHjmUGCcq1KCH8OvpE2rfjCpvvw==,iv:/sy1OLCM9wXVpJ4B8UzfTJO7BMh+/J2qCeG8pBZLcIs=,tag:Cynmo7Ec48iyrNO5G0gcvA==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWStVbndkTXBFRS9EVjJL
        M1ZSVTNrWEJvelI1V3ozbXpSQk5aYkREM3dNCnk2Nk9pVk1WMnY1TkFHU2FsRGZM
        emhmQ0JrMEJNOEo1Y3NFRDBsdm9oQjgKLS0tIHVzaVZLbFlDcnFlKzJRUWVCWFpu
        dXpUTUFnbmJHaTJsd0dUVC96UGtua28KTxwKs4OkLwIS59nhZtjw6wR7QI9R5VaA
        9cc0vbtiFSQWiTnpNSn3udr5ZaBB1HRSpnNjeCfwiRzj1PHnL+gXbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T18:26:44Z"
  mac: ENC[AES256_GCM,data:N+9bard/AhwTRY9BE9QrC4eyRpj51zjtMDa8+coVUCZi4gJaWPPVlMh9ufwdIvKhbkm3ke95N0Y/J2PYaBAFIl06G1IzFocfk5yKkxajYjOoNcfCMvrhfqhXAIuwSrqbWtJiRS8U2hfGpJDpCpcI9sEHd5ujLokLLWMLbhh/tn8=,iv:2Ikli0leY1AgzxwyMRx/wPm3+pqEy16vdhyQnhCyC8k=,tag:p/YHKmMYspZgYTXxTD8EFg==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
