# yaml-language-server: $schema: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: akahu-actual-secret
  namespace: actual
type: Opaque
stringData:
  ACCOUNT_MAPPINGS: ENC[AES256_GCM,data:Ibm/+AmBISwCT3p2FHtHQF6aKRrJJar+6OxiLE6fvpIIdVe340QR6dGZxB8PfkVRZyJ/DzcO4EJ4pt+mnKZICGIv9ZIiMbJTqPtUVF5M5fchrQ4pzWSPjmw+dhNNwXyb5Z9SbY5E0cT2AwkZ8qzDCdOUqRsRCsmjfdwj6uBJeCTRUhkHS4ocGKXp8qmYPVDU72mjuDgPlZK5t3hLe/YAGVBMB0YidGAaafgy68elqGEhUkbOAfHRrDiW60lZEZyCPVGfkDFm/ulMVZrWE6WvVJn3G8gVwpx6bSBkrq61LDJdbv1AeyQ1G0Nba4HvshKBIjz32Ed2G+hBZj+vOQpgOvacy73qyZSYxx6WLZ4onzyQBs6DgZDtt2gDKMK9,iv:iOUMy8MKqMw145Gwqi+KVdAfDdE6foI3LYHsEAJZFvI=,tag:ocEBVKeA5X1Nmck67DyvJg==,type:str]
  AKAHU_APP_TOKEN: ENC[AES256_GCM,data:V0dzPJvlIWvIE1Y92EARE4Gb/czs2q6JCG2KJnsRVY2xPVI=,iv:NLnPmM/AcdnwYZA7XL9AsIjlmQvAT9aHF6a5f953oHU=,tag:1+k0NExWm3D/Q9WzNcn8Gw==,type:str]
  AKAHU_USER_TOKEN: ENC[AES256_GCM,data:DnJk9JAdvnBnYAxeXcfAs7KyXIR8PvQmT7bR5rnQDhfQM7FH,iv:7I5WlOmAWkaWJgiIHXUWdBVQ+322KHPuzttvr41vnmU=,tag:Dw1sYT+pzpSq7A18Tp6UKA==,type:str]
  ACTUAL_SERVER_URL: ENC[AES256_GCM,data:slBkWt7EQsxv1WFkRjRRJXHVZvRO/LzIo9LFnjq60bW1IpgH+BA6+2vijQ==,iv:8CS/3B3D2SMMhzKGNZpUphF7nSqeXGNJlaO8xm3b898=,tag:W0FRMYJt63Msc5E0HTdZ6A==,type:str]
  ACTUAL_PASSWORD: ENC[AES256_GCM,data:pWUv9H/0RBQ7gkRmA4gORJQSKGNcsLRZCA==,iv:LPSbvR2TE21f8S6O1mu954PC1MDMxlr3TSAGwbb8jPA=,tag:TZZI6SXYf9y7alJgO+BO5g==,type:str]
  ACTUAL_SYNC_ID: ENC[AES256_GCM,data:bBWuwmSW3Y8elF5B9c+c7kYKTgssvmgZROb9tsKEDmJ4UzVj,iv:pZU/KeZ2akcuBBQC0oDW3ROCuyMdrTPQjYQsWWeMU28=,tag:sYJlJnoNk+BctdN4g7ObLw==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTHVmR2IrNFF3U0xwVk1N
        M0x6UVhzSWozdXpSRHVHUHJIV29rc1kxUkhFCjNLR2xPK05rU1ZWYUl3Nk1jT2NK
        U0ZZK0JudlhIcXNQUnNFQlI0bGxLWTAKLS0tIE9sVmxCVWZGN1d3L2c3MC9yYm9i
        a1BQUW4yRTk5bkVRdjdUMUxZaVRzcG8K+v0PeTZYMjstSL/7l5XK965Tp0txkYPJ
        QCwGD/tMMIYzJb66zlC0frzgOwtvD6tGwkLxzon9WBIBbS/BlLKMcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T18:31:10Z"
  mac: ENC[AES256_GCM,data:LndBlupLwj3yZ6RC6ccCfpJjbF9FIo4pXLpPLw+gVJTkFyVOWmTqPU51TO63wGEVY1wFNSiojIDY+GG+lBEhFLbejWce6qUxxdMtrIXhBg0EjpalqPjrfFAPKWhxYtglOa4eTexROAH/riopVPaynGewWkJhSyDE/UwFtPblT1E=,iv:6IBo4+ZJm2QVgU36KAMx4J4em4XJ7ZFF0fRYDIqciqE=,tag:D7C4qTy2YV/mye8Q7ipktw==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
