# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: restic-media-sonarr
  namespace: media
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:cOcoUvyEQe13oB2ObBwXgesQqjaJ6r2DRRGeyxzQB1lxxdfCQr8zAeu+iWqDrLwNQ5WIx8H9zQFnO0Y=,iv:ybemJyh5K/IFIqeR+2ZgAsJY3VWnEvbb2syZNqeZVlY=,tag:Lu8Y8p+2bErdP+NRos8mZQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:fySK4605fC2XQukm0d9I+RaQqnZUqYM/xE4BB58hKg0=,iv:FVk9ZRR4GF9VoGSy1zEGBeoujd6M0d8poW5heAkdktI=,tag:GBL37Sf3Q8DNQHIJ9ijlBw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:g8/T3Kf0wMx2J+2WwSDeYl4mXW3pdJ0vkQ==,iv:3rFKhsTw/eOLffLpbf9RyVeu/4pdMDAW7Cp02z/UZEA=,tag:ielgYV/5yIzS4AafV1jNwA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:F5YwcLjRdn6aXWmwNbdK7HDhnk/A+jHdoKR3a8/wTw==,iv:94JG5OrV6cjz2T4lbk+iOVK8gGLxbSWsd8aXVeBjDso=,tag:YnidJYwMo2qaqG8tThTxLw==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UXliK25acll3MnM5UkRp
        ZzJnZkR4R2JrQzFIUS9HSHpla0kzalUrcVNFCjY3OFhXdFBZRW95WHk3WWEzd1Rs
        N1dpam9zWVJyRytHeDR3VkFHUlF4UWsKLS0tIDBrYTBWL2RITGE2ZjdXR0NzUFdS
        TFI5N2FaSmpSdHVnc2d2bEJWQXg3S1UKL+e11swgS+bngppmhAsz/mHTVrRgIhQl
        D2LgoXqHW7sSDVSPKd3ozATDIUa0g6TsEkrG5BLoLvFVgY8XvePspg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T18:26:45Z"
  mac: ENC[AES256_GCM,data:V+KB76+09F43zXuWJy9S3KMtr40Qrhd4CqWSLUFiPac17iVETwUgoksp+Uk3uRWnamofySVgrmS26LKX9N5AIz4RZL3ikKbEe/SjTTUi9epnWaohjwEvytZS2+hB1wybvlQuwOD8JsBm3OFCsKLHhDecPagTmneFmGKfvFTn2wQ=,iv:pwfvscMZDqIbLaaiOUZio2pA3Dse0hwn/YN6geG3nx8=,tag:9sboJ2yovcbiCBzbxwAvOQ==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
