---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - ingress.yaml
  - pvc.yaml
  - backup-config.yaml
  - backup.secret.sops.yaml

components:
  - ../../../infrastructure/common/backup
