# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: sonarr-postgres
  namespace: media
stringData:
  SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:FDNeNd486YwGIqzYX55L8FEonTmQ8WZpU3bT7ppS+FoI510DM8gTEQk0Xc2FRGIzOA==,iv:ChPIRVley28d4j9CRIL4c+CTnrbtp/ODR01vxVyE0Os=,tag:1ldFNt8iA6YvPUwPgOSg5A==,type:str]
  SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:URk94g==,iv:cvN1LF8zo/tFSPONhTOcBqcu01K9Zveg14Ik8Mz1JZU=,tag:Jf7iZDQfBuhILQJibAgXPw==,type:str]
  SONARR__POSTGRES__USER: ENC[AES256_GCM,data:txyoQkV3,iv:gXWACw2Dxqfu/gijcVD7zGQ5V08dBFs4u9o7LIG2GlY=,tag:xcJ5qTxLQtpUcn/GNWBUeA==,type:str]
  SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:In6w8NncMvPGDiV+8P+nDgg2NwVL7n61,iv:CV0cHlhubbuSCKl2qDcgrxJCr06wAgTI4KSTHK9w9Sg=,tag:/g/v5WYHKrvVYWD6lhcbvQ==,type:str]
  SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:mLlrtmUn2Z2Sx18=,iv:lU8LZQmLRhpOP3M/WJ5U5VkjJFIquwUjHmGvFdqBoIE=,tag:1IUvXgUlO8lnkpMFLk2ifA==,type:str]
  SONARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:sZ026KfN0IgsQw==,iv:sBub2V3CqHUAP33bzoMDdpXfo1J1oiBvMuQWjs4RGjM=,tag:AkJ9FH7QTluziQ9GOCoVCQ==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVFRpVFpEQkNpQTUxT3Vt
        cU1HM2Q0K1JoOEN1STRXS3R0MWI2cGxpK0RnClAxU04vUTE0cGRKejNUeHpqb3dL
        Ri9TR0lmcG9zOGdOeVFjeXZXcnJuL2MKLS0tIEdNSEgwZFJlMlpyOGdPSVN0VHBs
        VzlEUHZLMlNPL0k4d0NEWmZ0YjFYYUEKo4LTN8BIu0JoZ86OJJWx+PFmj/T9c1of
        +r6VRkuQ5qGXbDPoXb6pslYEhlfhSf4K4sAriibFAZ9ExEpCr6QCuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T06:39:07Z"
  mac: ENC[AES256_GCM,data:iwFl7YKMWCJdwqNT84SGzwqJFRHPw/mlnwXrLE32+MMlAvbo6g0KYW9Xp3XZShBitb4e5riyz/X9rvJ4cvjZ5qngSbLgRIpnDjgHyn+mfIFRvAIanvAUq915yLbg8VeGH5XHyOO2pC5JHQnIwXaeQDUiE1r+GyPFqfbdC/fTW0Y=,iv:rDLtCb++at12dpfHLFT2VQ+TpsZPMFdu8OGjBhwGX0o=,tag:ZtSNEHP6gBzwtl+9PLXpJw==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
