# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: sonarr-secrets
  namespace: media
stringData:
  SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:nL/K6x1n8Oao5Rh6NUnbTLKXXnOoUxZ1XjbX2L8HkrygWiwCOKt7skq7kjJlCvpL0w==,iv:aA+UPncRg90W00wkcgCnhNSd9Y/xElJ/BtQz32iNmsE=,tag:qxnsQMrPD+NNXWsd2cQ41g==,type:str]
  SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:LxyB9Q==,iv:a7jMSbTgsPQ+DIEixhGnlgUeSrYaD6BAXf9qoe60s1M=,tag:PlG3ltGQqQBAhbx44Jg89A==,type:str]
  SONARR__POSTGRES__USER: ENC[AES256_GCM,data:BCOQQp9C,iv:n1XbKx7SrLH3DTlN4NSg9LR0SwDJ5ZdZ85zRENnOMlA=,tag:NOPFxzqSbWinpeQg2xYFiQ==,type:str]
  SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:veEdWq+UM54g6QjQ+55R0psKBauiNLU6,iv:8+yWslHqPv2LFy7kBvqn+vWJFwVz2EHd8NCj3h/4LDs=,tag:8+7JrNITXbNlgeYhSHu7fw==,type:str]
  SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:WwSfbnYHVPDuBrI=,iv:KF1gZN5EJQ14e3XySYCtvKYhmO1j92E2l9d7oF8hP0s=,tag:BYxkErHm3ZKU39h4WLI+LQ==,type:str]
  SONARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:1VBGSoFgGv4hUQ==,iv:nPMxrLtLwvpdXiwnX1jX/pOXKPulmv89jSvpFPun4vo=,tag:ZYtDtHCrtTRifpuxbC3d1A==,type:str]
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:cBAa2RjqLVBXZUYDsVosrI5GiT5JivabqWFdj5xI/YU=,iv:PFPqd/4JdcbQpjXTvX47d8oYMn5aW7rTIAgqrVCR4C0=,tag:VBCxrcIbmf9V7/cd4+thJw==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUVl5K0djMVltbW1uKzRi
        cTVNbWJmRTVvcTMzSmpmR0lBalg0dkZmTGxjClE3dkZ1T2ptZzkrYWJyM2ZFUG12
        QlNXZE9zY1VDY2g5SktFTElsRy9FNVEKLS0tIEdYVDhSalVrUGlHRGVTeHI2REh2
        b0ZLZmljVzZUdHJjNEpxbVR2eTdqeWMKXrN/TX+4lDzpyippqAsngW362BC7hGoq
        AEhPfQcjS22gbhZLiCPQb6X/ArPib4OtJI1KD/Hey4n+T8y7KX7sCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T07:42:19Z"
  mac: ENC[AES256_GCM,data:mm1hsV4qKIfsXGocd/ccu+FwUtMNZHCmm2g0iAhykeMRmdSESyNxeyH8De6HQ91/61cfhPn451Blik+qAs+9m7BN6pRWj0jMDSVedxPDU10nnqtbF44NPiigydJiFqlBvbqaadMP/k6jiZnP1o93DOcpkerSJ2HIJjVTIW2jeh4=,iv:VuE/9a1KtCId3TcvIJe0IxPtlzfswXGYuMW6vGvA8lM=,tag:ot34il1rmUHb0ZvOkBf7yA==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
