apiVersion: v1
kind: Secret
metadata:
  name: azure-credentials
  namespace: capacity-fishing
type: Opaque
stringData:
  clientId: ENC[AES256_GCM,data:SeF1Qs1nTUJSSUw9n+BW+0niHCZfqRTuKCmY4yP+SAiGeMow,iv:f+1C+6r/cr1T5y+vMhK8QxkVZsKWrwBXbPhh6//uZi0=,tag:HAwIZBSRv/yBCNf6Md+W9g==,type:str]
  clientSecret: ENC[AES256_GCM,data:TTRQ8bbh/+ZNADPF4bH6NmDg+qDb3aI5M33un9YaUnIYv4J6cmV9MQ==,iv:4H/nCvPbKuQcgX6bQmTkagULMoc3KWMrG5Ed7GdrE+Y=,tag:ewSpGGwswsTWq2kkdLgdSQ==,type:str]
  tenantId: ENC[AES256_GCM,data:nN42ulFkH6/eupkiuPO9jgMIMaVNm+kL6D1i1asTz0YXe+EP,iv:a5Ew4pKcL0f+dda1Hw87kqyxFODKuMWnWLnrD4jVnbo=,tag:EhmKrFLcSZak/ydYsjMsLA==,type:str]
  subscriptionId: ENC[AES256_GCM,data:fNH5uNqGFqm8q4UpGkNSukgCm9nCoJNQdzVFyCt64wXGxJsQ,iv:2ovbz4pAgKqVvL1kdAXu9+ookRicnSTfsBmzMOwW3ec=,tag:+onfSm5ccl71EbJnkcFWuw==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYXNsT3NMQWVHb0dhby9M
        OFVhYXBnVHlQYWZQUkxva3VrWEJsd1RFVVEwCnFrWFlsaFFDS3JGNlRnL2JPVjdU
        SGxPZEZrMVNtN3dVeGNlWUhJU1ZnYjQKLS0tIGszZjN0QmQ0NlNxTFQ0QkUvZHFB
        U05temlza3doeHpPM2xmSXo0aVVuZmcKgyCvEEIJqj8qn8mnKMKzC5t3IKBd5V4n
        vlStUorLxuw6Qd+om2RlP61RQtAVPjCcqhLYOtiluxb1lexJcNg3uw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T02:44:09Z"
  mac: ENC[AES256_GCM,data:AhtDRUUqchyvDlcSLEqA60+IzL371IBhVKf24AaPjfbBqBuSJWSTh0uAnrkngxusFcdDBa2DGDtJIQ9+r0vhaFYFHgR7Xw+riHcPO9zTddZxuHPGcL7WtpsZBkAfPo3+VI9a5f4SBYefKdAaI0SLttk8NbIsDrKJsr2/IrhodnY=,iv:EriGFOrsB/pSYmWNM0/EqmmlYH4OWijP68EJLtsYoeM=,tag:TCOW2laT0kDjzM4PwIjssQ==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
