apiVersion: v1
kind: Secret
metadata:
  name: deployment-template
  namespace: capacity-fishing
type: Opaque
stringData:
  deployment.json: ENC[AES256_GCM,data:iIuOlef4TCkJQpj//pPBdPTztXWXbmVw9MfWXmLdEmXeneQnwiIFNKTa5m1JuONxbmyTKNPMIE7oCb7lNu93QY/WGse6gPbk2zsg9NGBtHRPohw2O1FCZZIad+phNO6/jvqA2szrrelrcAFF2xhGkLYvrQJINHgFldqAYEGlVMUyR5nsdZyxjdkvmBvbe+yX6fNrEMyUD/oxBnMPZH5F1rQSxftW2VmMHtDKmH47S7H4kWPivLfKd2RM6kDLg/rEp0yJdX0nQnUc0RbBGpSLON3lIANhyyxRqdao3wOf3S75AQVXvLDUn1nZcFsUk7sLTFtM+eO44YGqdDt6atsO5j5/rQ8j7H1P5FhMFh++4WcPpQfkEbjwUMEIk7KIrGTb1ZY0HOeySYahCKRw+WpoYpvJ2eqNFsqGJgw0L+L5iEsNOO7jXj4eGfxoT6Xs6VuTZ0OI84Xm69K4+aVUVUrEjpMR1C+2x/fArF7lTyMc/szyd6KKHUTE6LknyU6v8ywF9xt6nVZypRmT8EM+zUXZybquGHQx4TtEQQo37DX1FT4tAghbeUldfXOAZybWRvAjNxr0wQhRbYcwb48cwG5DrfvZKTmFom+aUUJmPZrTgcWX/FRNIhuJ6pc0qKyImP81yRoGpH6v/cuGyRO2a5SddV7IHP4nBPR2FMxLvMRhtJ2Xdd85MXqAnnlFcuO4C7ELQOWhAZjJHUd43sZVFNQXEi5ff6wOYuTpSeD9Z3RYUv2yywXO3JoMnZb/UFOgHS1xtPvnoysKD2eYUbufgXiuw7d4qBbwVj8Z3mCAodAPN5VYMp7+tHjBxviS4pCPYDAWDIc0STgl/Mfopi935/pZS3EE9CmsqHLJvGhuOj/ou8USLlAxenA27uDIOpVldTPAUkXwkh3jGBNoDS9Ox5gFTbGuCAMIWHZYjYn5d+TpwKz12kSKiYbDJ9PH29BaIs2evby0G/JUTvDlKV07GcX4Siev5MWr93Kxk+91HTVMI5fpsQGSVWz8ZHi3ald0av3dS2q/8f6ZvAnFfEyuGYX53rCyi72CgvfNczUDD+Sq4avpsEXgfzfVwY9gt4J98UgErMYfQYOyFrdVqiP+m932QH2rPPXdPzFXXxu7xesz/Q/ps4gKOWvu5BLEGu0QhB2KNK0/6TsOw/H/wFKpyV6hAz+MUbmGM9OjZ/LehEdLTV471V4Kn7zgUoeLAQEDCxgBnnJ69ta13uY0rGB/nOeO6QnjzlWI8qj8l01L1zkFE8iPnkn0DxNYyA6hcSciRnZy+IOYbiQoT6BXjt4fsC62igs7NlwdjOAdns3ISW3IfnqZXLNTbAM/3PzN59Q5,iv:XK+SrbRVXoqTSO9yx1ero0hYlZIDQML9iXnLSMDptns=,tag:jHPoPi9KHqnJzV8t78uj2w==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRGwyTHRaMjF4bjF1dnBl
        WHJuNDQ2d3k5RUE5NytNV2xHcW5wVDJoaEI0Ck9vSkdPc1ZPTkxwWFlqaVJzaEVa
        Y043ZVNFVGQrQ2FaMmk4Q1ZoVnpGOFkKLS0tIDR2WENyZFN3aVVrV0VHT09qTUdF
        RDhSVkdZVlNxai9COHNxeUpaYU9VMFkKEESeURSlx51r7KuXJtocgfF/JTmrpcY/
        dmdnJxwXFgXNpfiemCdZPUdzxUwZTqHMx3CZKPfRJDNak+FKzP09xQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T02:48:05Z"
  mac: ENC[AES256_GCM,data:W7NNIb4ZHZ9IK2EJ2MnPV9LBbyHhNfW3ozgKbfCFU7RdzuZdpPzIbA6FAJ6G8laj2PMnGmG2wVt+F7k8yw5i9gTjRHObkT+N/uj3LQQwCgt+tkYZKr488Of8jEc2MhnUAjQFtJYQBzx5zxffXiwKeszgoh7Cg3xDof82pejdHtM=,iv:MOQkm433wyOBX6sBY/FGeWmPoPUASvEQCBwvHRr4hI0=,tag:hUeoJynRS7ypaqV4Tv89IQ==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
