---
# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: traefik
  annotations:
    gatus.home-operations.com/endpoint: |
      url: http://grafana.monitoring.svc.cluster.local:80
      alerts:
        - type: discord
spec:
  routes:
    - match: Host(`grafana.axis.scottmckendry.tech`)
      kind: Rule
      middlewares:
        - name: ipallowlist
          namespace: traefik
      services:
        - name: grafana
          namespace: monitoring
          port: 80
  tls:
    secretName: axis-tls
