---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ccinvoice
  namespace: databases
spec:
  name: ccinvoice
  owner: ccinvoice
  cluster:
    name: postgresql-cluster
  extensions:
    - ensure: present
      name: pg_stat_statements
