---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: gatus
  namespace: databases
spec:
  name: gatus
  owner: gatus
  cluster:
    name: postgresql-cluster
