---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: gitea
  namespace: databases
spec:
  name: gitea
  owner: gitea
  cluster:
    name: postgresql-cluster
