# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: restic-cloudbeaver-cloudbeaver-workspace
  namespace: cloudbeaver
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:Rp8MYo0tWoRUI6RK6eIG7pcvrgjcx4Z9PijODIBcMOLKIfZjeW+RrOS46JY/aTAcXxzYQJByfOqX6A==,iv:PVbXuIwXIsSB3S8CKvfAlYUoPFBWBO8eMWSTPKLZrnQ=,tag:q521PX/lK6v05c8PHgNCHQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:WkIJG+fRwRVDEvdiy5TJE8iq2Qn9oQJyi1dH7SzVsXc=,iv:2sAws13St1y8JG4xDU7UdUY6f/vJCjECy85TfInXcOc=,tag:BThpHSbjdbBOx0A7GM35KA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zo29bZKo3zmqXSOFR5QEadq6VXbVtpOjrw==,iv:wN4M+tGZAOoDFtprDzJh85ee/vUXZbGmj7yV5d4y4Ns=,tag:GjWyMmCdqWWXJ/8bJUtzcQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VidFKsBr2K0qNgsO4Vgq+te7idVDkDziYC2bUYDAnQ==,iv:iR86fglOwLtTmwmAWaZ9zR8sHKZO8PTe0aKbg2ulV2w=,tag:iSVcQyPhKNQljasQb84PpA==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YjFEY0trRzFRN05TNWVs
        VjVvNy8rSW94Rm9iNVBjZFYrdFZXNTBkNTNrCnRqUWdTdlZybmxKNlViTmNiZk5x
        NWxpVEtONmxIdDI4RGRTUnIxMWZpcFkKLS0tIEpzYXVDSGNkNUE5a1NDYi9KN1Mw
        QUdwNFNMUFd6RVNrNmtyWFhMUmlTOVUKHOnKFoWaNsqQoZ071WLcebb0IoKILMxX
        Yab3Kc2nqQY66idhV0A+pXrRZgVZZ7wVPJNXIL+CqiZQaO2Q0rK65w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T18:26:45Z"
  mac: ENC[AES256_GCM,data:isMlX0oR18gB0yg6627lQ5AgKEuJxqDrA3cnVRtTqlJMt7kwISBfaV2jnWKiUjCBnxPl1Jk9gaCF1J7bc4Xp8ULMHL2MFnv2m6HZ3zM7Lg2sCJnfFTtYyp3QhmD1SCsattp4dNrhg9TepvDVQC5bHCkathWePST9OiR2wHajrkw=,iv:fA/st1WNOfTutEESNqWmcv31QcN3s9X9YeEbglkCV/0=,tag:musRk2p7XUgUKGBi7cQj9Q==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
