# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: restic-cloudbeaver-cloudbeaver-workspace
  namespace: cloudbeaver
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:WDHPYz4iQIVZhukYK8g+Lf8B6Fn+PFlzwepOa3LRXGGUfGoUDHNn+lWh68gColT5396DIrERTL+iqQ==,iv:2Qsif7hwwLJZRoZhk2FlJUOQXr6dgr/78Y6P5i4eVLg=,tag:2CaXTfmkxkU4hSi1Rk7fHA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:RwOF6yyze/2qMQuqQteoQ0Yd+HmEOJbluWdaBtvHUfY=,iv:+GaTg5KAusdqcqnmugDuIHS+LKFFPxk21EHgc/JyR00=,tag:b/NyFXS89lfYS9IiA+e7Lg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:HgTFSnu7aKeF90j0kO4bbkYEFxg0AgvV1w==,iv:htuRJ7dlD7Rvs7wBLfsj/ZbViGTfDaLg8OsNsr9Bppg=,tag:2JRy8PRXHlUGF/PNYdz+zQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FujpTLw6zzPpH4lSZRt2Xi4jiW4pxKPAOd1AZssSFg==,iv:nDsOO8zVo9vXr9AxjpOjZclk9sQRiHxunQJd4hoaY6I=,tag:esbAANBiw9K++ZzLuAFipQ==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnU3pPK2g5K2loYmNHRWFB
        TWs1TC9PTzVCZm5kYWk1SlBWWkhNU3BzdEdVCktrODhjaWoxTG8wWlExOWxFNDNH
        SE9MOHVMVmt1SjJZZFkwSm14RVRMMGMKLS0tIEZxcHNGVG16MzJQelNNMWxXZER2
        ZkNiWUg5a3BmQnpaaGxUVzEzak03b28K0F7Cm0LmWZHbkNV8qo+a314Ulfi3FUQX
        xZhBIVGQ62oh1BL7LxujqPJOV7whIIHy5csG4awauqMowxoeKyfykQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T07:43:47Z"
  mac: ENC[AES256_GCM,data:RUOuHyS0uVsyFIdBSNHYhyAgU6AGeFqdnsGNEsEUDeUhxUvVtN0z35/RMnFI/t06zHzIIrxi6eq9BkyKlq1d9b12y5Q4xLzQutrRh+8OtJEwoxLk8NA/6OUjeXLCavWkSaWfDzxFSe4iIV7Ed/dz8dFpmIvFnetVLbdhA6y7XEo=,iv:mGMchjpWYfWmCVUDU4JnMJifD1qfe3BBTDuiTf9PrUU=,tag:lCJxgrrj2XEbhLig9qLe7g==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
