# yaml-language-server: $schema: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: akahu-actual-secret
  namespace: actual
type: Opaque
stringData:
  ACCOUNT_MAPPINGS: ENC[AES256_GCM,data:Kmgh02hWr83EycLF3z6BtiRtU5nwCAUebv26HvlLcpfkzD3IbYM3rGdWlM1v6zi1rDDLKKi8mWDa1vn8nq0TK+yX+J/TydMw16JDnKU4WF00wgdqODjYec9TllgLu0RdOMtNtG+4h4dUNLTV4PNAcoLv+8FjpoecWJB7PrukjmzFdwC7hAWh/8I9TV1Y+fycFdI66LPI7jg7JN41K/26nh4e2/VZEPOYeuSpSlkF7Mv2PCKMlvrh6WYkzncWS9c9ifx6jYIPW7LUy8Dy8UBg1AQOCizjlJjfMlJ41DH2zqDJrIEMTBcru9wc6RjAeW2u3LUoHu1uAl1USlsc5uH9+AlT35oepd0FpUStRNzDrOyT6olYoduEip0zzrPbkOOGveJPvvV0LrSc31tDpOOkVgYkLiS/oX6+x9TqhrxoETOJiqiMeB4NQ2Dy27jWoWOKGS5exbPcSXxWcl5c0JXnUof3jcDb6cj8oL2u9pUfN6Lnzshm4QnbOGg9E8CLnkUjA3d69bIjtvP+1mL4ldwmcJL4IGuR3Ri4/FsuGbdE+fvISowMJnR0zNAJIFMLnj+q+yqkLk9iaCrkF42u2QKoz+WJWi/lJIFRv4rnbpj48FRjuWLbUdFbBsWTIhLbltdOVeqOeKeMxcPAt0vDTEWktggYhAFPhw71DQgnAKDO9zHL,iv:zPBtNORB14v1p+sdIK0Ri39qoa6AvXEvsaFwmULteVE=,tag:9wo2lOzBSach2kPWvOkfcA==,type:str]
  RECONCILE_ACCOUNT_IDS: ENC[AES256_GCM,data:rHw/KAWkfQkHctBO4WBoZByo11Sh9nBQUibFwz0kj7uDooqXj6jYntBo+0SCkRfvIPCTopmFh2CQcVf5HRFA6LVNP6kCiq9oS0YoNacvhMkZvR7qpvf/teWPqX4for9XpqCx,iv:v2EBQKNEhLr88lXo3qLvB50IGnJtSeg0TkD9rxjJoZo=,tag:m8Uc5M/+GmPa1HxT2K98Uw==,type:str]
  AKAHU_APP_TOKEN: ENC[AES256_GCM,data:N/qRbS69UhTCh2t5dbw9xCT4+f9RI8vUly6lTWL/jaaFvbo=,iv:P36HVzdlP6qcoxC2xYHObwf+YmCn1H+rCz6CnOv2XDI=,tag:SDwSbdXCazFyRBS4WKCLCQ==,type:str]
  AKAHU_USER_TOKEN: ENC[AES256_GCM,data:n0mD+IRJfyHFjDn8TJWoU2YcOAHv/PvQUN8pJHUdZFTIOMKK,iv:8TWuptur/tMhW6EU8Oe3H7IQozu3YnUBKk65ietvaoI=,tag:MK6TdkisMSIBdcPS9sIDqg==,type:str]
  ACTUAL_SERVER_URL: ENC[AES256_GCM,data:eDHlUN8IlG3aQtEstqMdnfHoweRhDUEpuE5ZaJeMRnCxpDokoWbndf//Sw==,iv:Ke/I/++OwUuzuyJRRDfKAO3dcrwNLptlDKE8WZORnvc=,tag:Laredc07t5RxlhAFgn+Okg==,type:str]
  ACTUAL_PASSWORD: ENC[AES256_GCM,data:9pCCgg8Od2VL6reQOdgayDXLtZ5fbQRKrQ==,iv:A2gC73788qObGgEc2KH5UJ8TKbhhEq1rstoRTsUJT8w=,tag:jhOjKyEqP7A4f3YsfEpACg==,type:str]
  ACTUAL_SYNC_ID: ENC[AES256_GCM,data:SIKeqLtQMf71igb2gqLy7bktRnqrCQcQ9+E/342AHzv3TUxP,iv:ObXd5nvAVMUsaKIWTluab5knSa5NTCbzDuslNVBS0Qo=,tag:WLihf5MpCIxgTQXjZ/XgWg==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudWtHa0RjazJaa0padFpi
        Q0g0dHhSS0JiNFFEUGVIL2dFMVplZi9kcW04Clo3WmJnYVF3V0ZURktKOVoyVTFz
        UmtqQ3JBdU5LQUNwSmx3RVJtTDM2RWMKLS0tIGZFRFUrSFYydnRSZ2wyMkpRQkRo
        aVNIc2E5cHZVZnpOL1lZMzdkbFIvakUKnXU9H9Uaw7HeqhLFsp6rdE/QuicHkEAi
        dsDMt1+2TvJBenhRrJkiWZ0pYOGt12r8GLVfxHhVLL2vEecOF4g+Zw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T21:39:24Z"
  mac: ENC[AES256_GCM,data:tW1kWpj+Jafz4s/Iuhg9ricOD3Kf3gvbYXvfLfh6IFOVQP+wj64cAwQ2VoggMjhhQT4PF55kiGsyCwAuAH0QHXSXMhL0jL0BHV9VbH6QZqUagwymuBstwf+Ypl35gasxR2xuZ3B6yQR3VLWnlA0X091+7W8Z4uELt/un3qQB6fQ=,iv:/+aSSVCij0uyPbybRZbgKEuNAt+iC2Pn5FxvzaBv1+g=,tag:aHBbUGZM55lV2VLft1mt1g==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
