# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgresql-backup-secret
  namespace: databases
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:F+sSPJNjVIqnvbF62d/zdAeJWSTZgpzePw==,iv:+ZFyWGRESJiBAenAHOxcY5t3nPjg5RHA7Vgjo6EgJKA=,tag:13rk5G4DvYnMXIyE30pQLA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:88PjB4qzs0vWGz2uSQe5aFlMNPfAxAs3zNsZIM0Tcg==,iv:LPJzKP/l4KYNMFP08HG1B/Tf036abcb18m++UbBKpNA=,tag:jzDcXNUdrdYvtflQvwJc2w==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNTVpNzczUGdVSm4xbjdz
        ZG1zSjk3TElzYjB0bGU4TXBUWW40STBpQ3k0CkpXVG85ek9UYlhNTGJoVmhwT0ZX
        aTZ3bzQrQTRmeVE4dEsrWktZeTI2NTAKLS0tIGk2ZlJCZU00cHRUazZnSTdPd21w
        aDE3R3BaUExWelUyd3ZzMXJnQmY0ZW8K4V5u8ZPqs9KqG17oiCu+qi5g93VROLrG
        qfyiif4HWm0Wrke/SIRjFvHQ8f2m59D8qYBZPykETBZCTf8J5rRXGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T06:58:40Z"
  mac: ENC[AES256_GCM,data:fl2ZQZPS0IoG5EONKHeZOr0CzzJd/XofBJFsd8RRwTbw2UENDJ9an45+f3pITf1bww8g8fTNECmpQ3oOVQxpCqFPJvS2Mnx6jf7zVbIwTQrAlajuP5JGLWkYUOGerZOkO2/p4lEG1eg4In89sEqd/+SuyVFTr0nl7l6MunC4btQ=,iv:75s7Vkxw+w817cDMvCWM+SuBmRTUCKNNJie+ywCoPOU=,tag:b8eNPN5CKTfzXKE8SBZLjA==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
