# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: restic-gitea-gitea
  namespace: gitea
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:RcvDWLzdUZ9yBw7z6/xaIZxLtAyew9SnfJLl+eblHrdQ9CcbD/tqQl743ad23BcHx45ebeaV4tiFhw==,iv:rUigPuyHe3rzfe2jclW+EgtMJ0D9EeGGv7hxBSeh/aA=,tag:tjZqyfEPnX504al67qGwMQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:mLWh+JHPF+eZKwx04+uUTdApFUt/HYt1Psa6ufELuT4=,iv:6a5j0oHPinxYXP/tOPrZPaWQf4SlRrzpLJxAopZIU2Y=,tag:tZfFKyBqf9CC8mD6F4h2Ew==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ezFCDqm4buHhst1ZbBTKU+LS0BcOl3Ffug==,iv:6DCt2bVKO8uBFGHasT54WSNwWMcUnjPQiPoo0Ahie5g=,tag:G7mUSJeA+NHGkVbb6vNzmg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:66r4M/OqBQjUf0DvU0pEdmUrfdyL2iVJ2QxuUmXXuA==,iv:gY5PSM573Qw+8O4dmtR1IHWqxLLLOU38zlPzv/G86gA=,tag:d+4XoZl5fvMpCizj6lNYfw==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSEs0VmQ0VkhQaWNFZ09G
        QTQ4aVpzMHB4ZEVOWGdtM0lxYkJWallKZ0NBClFzZld3NzR4QXR2d1VkdmtOQllo
        bEs4azFWTU5RTGlaRFErR0toL0FvWGMKLS0tIHZHSzNJV3BoVWhpZnVxZ0haNzV6
        SHVMOU4rbU9Mem00VkIzWnJkSU55M1UK5lSLTlZ8fk70yaGGMkTpKo+gSt4zRfID
        bG91HVQx4xYhtstGrfDbMG590gWrJHdtxyCHX8D4m5Ry+2Vm1oP4kQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T18:26:44Z"
  mac: ENC[AES256_GCM,data:RGbsAapOw4Wf1k2VFL8dPEceJKFmJweri3HlVpqjzUn+S2dqr011Vzvs6JopMIh956QIlGHumURrHLnWA2atJj4vUNxfbgJY/W0nINMJ7q2cv60JyrbMJaNn0OShaoWREQLSVPnGzyqVUTExUgQNhzCUFFZ5WTtCpLQvU8BqG+8=,iv:UtXeZAmlweEnhkFH8G6bl/vbQeFPG70BjQT56z/OL6Q=,tag:jbBtLauA9K2T5kEVk400/w==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
