---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/configmap.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
  namespace: gitea
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: disabled
data:
  NAMESPACE: gitea
  REPLICATION_NAME: gitea-gitea
  PVC_NAME: gitea-data
  SECRET_NAME: restic-gitea-gitea
