# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

resources:
  - ns.yaml
  - pvc.yaml
  - gitea.secret.sops.yaml
  - repo.yaml
  - release.yaml
  - ingress.yaml
  - backup-config.yaml
  - backup.secret.sops.yaml
  - mirror-release.yaml
  - mirror-pvc.yaml
  - mirror.secret.sops.yaml
  - mirror-ingress.yaml

components:
  - ../../infrastructure/common/backup
