# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-discord
  namespace: monitoring
type: Opaque
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:qD2JEwRv7GJR4bVNM57+KvwO9m27BTDnsS6wq2/y9L5oBOD0DXTD91Wt6BEOiYsXHNyspkBXGX/EPKWQeAdEh9fNnEwaCH2o1vKA+2mLYSdZTY9zEu/nFOKMynQka3snMMapeaoXVvblos/EPVAyL54FKcUzcv9j6A==,iv:ZFXoxf8X5fbBZ96E5CtWu/6innIy0NCSBr65GVPbGsM=,tag:aZ7U7dLDyIhTdrR7Tl1xEw==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcXBqTlJXTXZSeUpKUnV5
        OXBJaWNCbXJKWWVOUVlMNkZZVXlmN3BLbXpnCkRtUStxanlTZDBQTkQyVVViSW9F
        ZHd2UDNSc1FiVDIxSml5QVF1RDM5UTAKLS0tIFhDbHJPTXIraTJwazJBWS9DRTIx
        alJOaE9iNXlGTkhKK0kzMWVnZ1BOazgKA7R8GHbtYo8+AvIuL6Cj/tduQ3IFjkzH
        Z37xLgPx0517ORa3xr9GrNKJCCs3MN6D/7AqJsXJoFHnRNPhUL21mw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T01:35:29Z"
  mac: ENC[AES256_GCM,data:V5Rfc1/+04XZBBzIHRtgh/1hJUzxHqs75yc02Ne0dqzkDBLOC59/mcP7EnvNfXXS+22s08t5QliH/VSNpQc402ugMMh1qN88DHPcDZ6GlQOOGYS7YXSO61WrnHX8y/QOeuIbNZpYLPVMmX1LOJoq7XFEcZA6p0Wk4M7Jeyoqpt0=,iv:mxjrodf1+ElIZWAJr6x5PhqPnkQrpT4BjKNkeim4Jog=,tag:Bkg2DlAwPsMEupxknORIhQ==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
