---
# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: traefik
  annotations:
    gatus.home-operations.com/endpoint: |
      url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
      alerts:
        - type: discord
spec:
  routes:
    - match: Host(`prometheus.axis.scottmckendry.tech`)
      kind: Rule
      middlewares:
        - name: ipallowlist
          namespace: traefik
        - name: forwardauth
          namespace: traefik
      services:
        - name: kube-prometheus-stack-prometheus
          namespace: monitoring
          port: 9090
  tls:
    secretName: axis-tls
---
# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager
  namespace: traefik
  annotations:
    gatus.home-operations.com/endpoint: |
      url: http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093
      alerts:
        - type: discord
spec:
  routes:
    - match: Host(`am.axis.scottmckendry.tech`)
      kind: Rule
      middlewares:
        - name: ipallowlist
          namespace: traefik
        - name: forwardauth
          namespace: traefik
      services:
        - name: kube-prometheus-stack-alertmanager
          namespace: monitoring
          port: 9093
  tls:
    secretName: axis-tls
