# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: ccinvoice-secrets
  namespace: ccinvoice
type: Opaque
stringData:
  SMTP_HOST: ENC[AES256_GCM,data:ZJvsYrMyOALay6WxAW8=,iv:B5bu1m5Pat8dcm8FGa1aPPHLcKJr/D5F7KCgi3mJ77U=,tag:3NkizkKcEhU20vcDwAGK1w==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:kVYh,iv:7b5UXsPvYmaZyWNb5VqOzeulUB3g6i9CnU4uKjLIfWA=,tag:jfuAsyAv+uxJX64bd8lJpw==,type:str]
  SMTP_USER: ENC[AES256_GCM,data:rswkv89rd2h+sMlGcPi7H2k9VKffWw==,iv:5wsNv8DIsD89c13e6Ig6/Ds88+HazlFPfi61Fy6dWyE=,tag:Hkg/OXkshTL4t1xMm+2VGg==,type:str]
  SMTP_PASS: ENC[AES256_GCM,data:K4DKG3NJ+MG6YmAHpV+wDueFAw==,iv:tLdElI5Yi/SOmnJV7e42qMYRl78GCXnN4xP8ldYeP/8=,tag:UlIkM3gDq0jkiIx/vRZWRw==,type:str]
  FROM_NAME: ENC[AES256_GCM,data:hu0OuUz7WpRe+SEs77IexQ==,iv:sj9tihFl4CjgdqWdic8iqTn4nqw/m96dk1wScqaQ1Uk=,tag:RNHTrzUvgwVqSqlSFzvnLA==,type:str]
  FROM_ADDRESS: ENC[AES256_GCM,data:HDpDYdGdkM8zYKaJ8KEun/ncSDPd,iv:+szXF2Sy0P4HcJr7eKw953VBx2ySAT6d8PCuyuDwbp4=,tag:j8F9/Am0aJxSQ2FxNsQdBQ==,type:str]
  FROM_CITY: ENC[AES256_GCM,data:TniJ03G5V7BB,iv:2YzNSHW3A9k8rEfLdAbCKx3OXhwMOcbq3v6YzmasVEo=,tag:H7o7e9PIW5dw9b+gYfEZ9Q==,type:str]
  ACCOUNT_NUMBER: ENC[AES256_GCM,data:1CjinziONggtKiLb+VSt0I1/,iv:MZuf9OHDwD+q925dpAOFpihtJaLADy5kHghEy0cVJtw=,tag:lbxKp5RKA7z5bkKSxyCrjg==,type:str]
  BASE_URL: ENC[AES256_GCM,data:vRiWcuOLBR06EbpQ448ov28x5/XPnidMJxOKRZfZNa7qfSSJxTfbaA==,iv:FLA02Y1hoBl5cLgVliM1SjINeRFANB7g0pkKFyZiNE4=,tag:TaVYug17KxrOnhiYGeiu+A==,type:str]
  TZ: ENC[AES256_GCM,data:N1k8DpF6luzk4hrsXPVcsw==,iv:azOmJs+jersX14cqe9mHGCOrklWJaAtF4naUdo6zf98=,tag:1BpHPn4mrIeyooJhCXOYhQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:y9trjEhy4SS8RtceO8Thoq5sgcunn2nuG5cwDmuVVudk5Pe6kWtSYc7uecXnzH3wj792Reo8GSUos7kAyYJseQTAQsOQiigqG1z7KVm8LUKa3+MoDBfzCK/Ji95FEzlSKI7HDJpFZKk53Ecwt99tqrwBrwz00hCp2ZX1sGP513iW6itdNO2VSGBevKMZzdrX20IWHBnJkpIcp8nFPxPvNJ7a8GBOwg==,iv:7JHWozFnnZF3qF086FO2qfVY4sORrtnyGjJ3jx8Sd2Q=,tag:vEwirDltZfG1zySaHwLmgw==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcVFRWHk1dTl6M0d0OTNz
        bjBrUXpRS2R2SzEwbkhrbGtuZHBXT3lmbVRNClptMTZpbXBPK3FKOHplaXZvWk40
        ektNKzlMdjcvY1k5Q0RsTHFXZFMwRkUKLS0tIGdUbVlhRUsxaHNpcEJzVUg0MDhr
        MUR6K2s5L1c0RzF6MzVxMkxUdFlNejQKZH/rq7H68OcYRDPK04V2kKdYs3SIEsDy
        VhK1ObQIeIz4CxYMJAjzWNH8Fquc/qwYoPnHGAY/B2cYKSTJvsIZ6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-06T07:11:25Z"
  mac: ENC[AES256_GCM,data:KggANw4rgImuJAmtl2qE2V1UD1uOLrL1257MS4UJ+Gky+0rLHJpJqskWtswpXQVayM0KDmQex3/qWuI/TvL73PbI0mFPQBZnb0Ajzzun3D/qUR+kpEQKA3XNYP7WzUxvJ3Xz/38IJAr4hS55qSTjvu78ujcTkxmBPXQ2phbkE90=,iv:JUPdqBifLXtl6OheQhABpcY/2swlQAmqaoTJCar1bVA=,tag:dof9ifojz9WzvDq/uUCO0A==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
