# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: ccinvoice-secrets
  namespace: ccinvoice
type: Opaque
stringData:
  SMTP_HOST: ENC[AES256_GCM,data:xXonUmU9XKBGt4ll0bQ=,iv:wi9uYS1nC77bDmjwdnt+7WW/UG5Z4P4TTsYrbmPfGf4=,tag:EhJwDGHNUFuiNBJP7iEQJw==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:0Kas,iv:cAlgX6QM744TDXJlKdiVUv0+8ZmOiUCr7Vb2lEKNgdg=,tag:k0nlqFvN20wDHnbT1VED4g==,type:str]
  SMTP_USER: ENC[AES256_GCM,data:NKZI6hQ1l7kfA/DhRk2JYfyVX0q5jA==,iv:IMo8TnKY/x8UBOJMh/4g4IXJYV8afphO++p+olCPNu8=,tag:baBC/A9ETFulQi1q2+p8oA==,type:str]
  SMTP_PASS: ENC[AES256_GCM,data:eh76YkxVQanhOCH9BUzc+PiY+Q==,iv:lFTv4Rgq6oiO5tKePXbLXSP5zZ33jVRtjHw5bFjUiIg=,tag:NtxQjZplM8JPVXh+sLh0Bw==,type:str]
  FROM_NAME: ENC[AES256_GCM,data:tIRu/fcvpeIowKKqmYXUcw==,iv:EYp45acH7aNqOOy+ltQ/XxFHD3Xd2rmvmxsIsxUGiLo=,tag:MvWfFWPh/RGhkdu8iDkn/A==,type:str]
  FROM_ADDRESS: ENC[AES256_GCM,data:4fbSZyYPh2/5xIOESQAnRT0j/lQS,iv:ediG/UpigO/MHa3bijTU8/dqdhjTP7trMGCnsw4H8ds=,tag:mivt6BgO0MaVehxVj+5QnA==,type:str]
  FROM_CITY: ENC[AES256_GCM,data:3r/+fw8rrj1Q,iv:so0EcOhsnQYkOGkW3jjXymGlVFOmh7jA8kk2tQ/AzzA=,tag:GrG3iWphgvhju5+J0ijGAA==,type:str]
  ACCOUNT_NUMBER: ENC[AES256_GCM,data:hit+b/GE6fyVRXlF2e2oOCo2,iv:9l6XpQAOxJ93m211oB3LwK5AvjfuL5T5N9gy1K2LFUY=,tag:STRFZDsg591ujxMLsrAikQ==,type:str]
  BASE_URL: ENC[AES256_GCM,data:l/fFA1k+3MCCik2oCJRNTDdLG+iakhTDr72KBUcJ131hwlBc1n8w2A==,iv:d+Xw/Kjm6xl1of5h+1WzDuR1173Wb9wUgo1Gn7dUrCQ=,tag:Twfcv4CvstVM/T47BjAnLA==,type:str]
  TZ: ENC[AES256_GCM,data:vCS0tMAVmsC8kC2S7WQ5OA==,iv:cc0srILOPj7cYuwIwfINGUSeXfMhUG8ZTD39VnG+hk0=,tag:8OkOH3jNLzGT70Y+XypNTg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:PzfVwRIvx8GUDzJqPOLA3tjZDs8NXa4cA2mtDXRg4G46/nYQuTvvkRgi5/CF4EFc0lMQ7hgmZMfzpMvHkALVdSmOb5bMygg5FUrvEJV6O0pvOM4E2D+fehH9gMG+F+g58qvd+5K+DoZp5H71vUvykFRooTR/QtqrNQM2EBOibEU4Slgys7YWUOohLG2nONn7kb0unTg/uNzdaGFoUMjI2HZFvG552w==,iv:H3QfxZ06jdbW5BN6tOR3Uh+lAZGlkmvQrob4W6KEM1k=,tag:H/L9C6xW6DiAT3cTE2SxxA==,type:str]
  TRUSTED_PROXIES: ENC[AES256_GCM,data:VSprH2pYAvrEOudq4Q==,iv:g3Zt/YFma0myP4/xhzfzYdEtkAdm2LGNNNKFgwP8udg=,tag:NZCmmkxoNlFCjDXA5o7QZg==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNUpqUFU5VnZpTk02ajBq
        eVNWbXNhK2RQaklqNDZ5bXFRYTRUb05tNGg4CllWU1gzRENDRWI0UHBMMkdwRlZy
        Wk1JQXJuRmRudUoydWo2cml6QTBMRWcKLS0tIE9WbjZkQkwwS0I5ZzVwVHAzekZx
        S3FGbmM5bUlRV2h6YW11WnBBRU81ZWcKcdtRcO6reStltJC/3vhKzzwPBAZJxd0f
        MrVSjdMdMKdsAQFXEm+3DBOhdhwcaVGk6bUAEc9UbmLlMnnIzTcToQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T19:31:38Z"
  mac: ENC[AES256_GCM,data:T3wKh+Z3N1kfWBn+FGq3mIC52VkFR1J5BaVgYEJIOP0TxzzTc8Yb2LGkP0BsDT9qxlco6br517q06PetkFAz6KlYrd8OOyN5LLBkcN8ScXap+xREmhfEH2NdFIMzsYiGnzD6euZkhvcQIWD+0hmESsxdqHmghebHdaLYzbsS9rs=,iv:L+0HLt/U0un5MG7Byoqt5vbrNWMu404UMblEqJ9LEg4=,tag:J2ncwPTtOydliNviUte59A==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
